### ISSUE TITLE
AddFieldToContentType is case sensitive

### ISSUE THREAD

**Issue by PieterVeenstra** [OfficeDev/PnP-Sites-Core#123]
I just ran into the following error again:

**Apply-SPOProvisioningTemplate : The property or field 'Id' has not been initialized. It has not been requested or the request has 
not been executed. It may need to be explicitly requested.**

This time I figured out what the problem is. 

In my content type I included my custom field:
<pnp:FieldRef ID="CBF538FB-8b07-46A1-BC58-5B4779C23AA5" Name="Price" />
            
rather than:

<pnp:FieldRef ID="cbf538fb-8b07-46a1-bc58-5b4779c23aa5" Name="Price" />

Looking at the code in the core project I found lines like:

 var existingCT = existingCTs.FirstOrDefault(c => c.StringId.Equals(ct.Id, StringComparison.OrdinalIgnoreCase));
                   
The above does make the comparison case insensitive. Which is great when you develop the template xml files manually.

There are however also areas where the following case sensitive comparison is used and therefore a field may not be recognised.

var flink = contentType.FieldLinks.FirstOrDefault(fld => fld.Id == field.Id);

**Comment by erwinvanhunen** [comment]
Hi Pieter, 

Thanks for reporting this. However, in the example you post, the Id property is a Guid, not a string. E.g. we are comparing 2 Guids there and casing doesn't apply then.

Which version of the engine are you running? Are you compiling the latest branch (we've been making many updates to it the last days)?

**Comment by PieterVeenstra** [comment]
Hi Erwin,

I didn't investigate the exact line things failed in but the easy way to reproduce this is by adding an existing field to a content type definition. And replace the GUIDs of this field with some capitals.

I'll have a quick look where the exact line is where things go wrong.

I've got the code as it was at the beginning of the week. 

Thanks,

Pieter

**Comment by erwinvanhunen** [comment]
I just did exactly as you described, but couldn't reproduce the error here...

```xml
        <pnp:ContentType ID="0x0100B5EAF2F41E01254D8D78342FD9EF8764" Name="TestPnP" Description="" Group="PnP" NewFormUrl="" EditFormUrl="" DisplayFormUrl="">
          <pnp:FieldRefs>
            <pnp:FieldRef ID="c042a256-787d-4a6f-8a8a-cf6ab767f12d" Name="ContentType" />
            <pnp:FieldRef ID="fa564e0f-0c70-4ab9-b863-0177e6ddd247" Name="Title" Required="true" />
            <pnp:FieldRef ID="A9E51afe-1c8b-4c51-9413-b630a82b660f" Name="Test_x0020_PnP_x0020_Column" />
          </pnp:FieldRefs>
        </pnp:ContentType>
```

Notice the case different in the last FieldRef entry. It just worked here. I also tried with different casings in the content type ID, but also had no problems.

**Comment by erwinvanhunen** [comment]
What can help, if you still encounter the issue with the latest build (we made changes to the engine today even), is if you could provide us with the template you're trying to provision?

**Comment by PieterVeenstra** [comment]
Hi Erwin,

I just tried it with the latest code and it now worked. Whatever you did over the last few days must have fixed the issue.

**Comment by erwinvanhunen** [comment]
Glad to hear!
