### ISSUE TITLE
ContentTypeUsage not available in OfficeDevPnP-Core component

### ISSUE THREAD

**Issue by jigargandhi** [OfficeDev/PnP-Sites-Core#130]
SharePoint Server Object Model contains class SPContentTypeUsage, however, the same is missing from Microsoft.SharePoint.Client.dll and OfficeDevPnpCore. 

I think this could be taken as an enhancement for core component.

**Comment by erwinvanhunen** [comment]
Hi,

Sorry for the extremely long delay. Indeed, while it would be nice, there's basically no 'easy' way to provide this through CSOM. As you said, it's it's missing from CSOM, and we would have to scan all sites for the usage of a specific content type. You can understand that this is a pretty lengthy process and hardly usable for real-time usage. Another option could be to use a search query for this, which can work, but requires that the search service has been configured correctly. While this is the case on SharePoint Online, there is no guarantee that this is the case in the on-premises environment. Besides that, it will introduce the problem of index-freshness. E.g. the data in the index is not necessarily up to date with the current data in the sites itself.

So for now this is not likely something we will implement, but if you need this functionality, I would recommend you to explore using search queries to retrieve the usages of a content type.
