### ISSUE TITLE
RemoveContentTypeFromListByName doesn't work when content type is in parent site

### ISSUE THREAD

**Issue by soyalfonsillo** [OfficeDev/PnP-Sites-Core#138]
The method:
public static void RemoveContentTypeFromListByName(this Web web, string listTitle, string contentTypeName)
contains this code: GetContentTypeByName(web, contentTypeName)
But it's not using searchInSiteHierarchy , so if the content type is in parent web, an error is thrown.

**Comment by PaoloPia** [comment]
Hi, thanks for your feedback. We usually do not target more than the current site in actions and methods. Nevertheless, we will think about this request and in case we will decide to change the behavior, we will let you know. Thanks.

**Comment by erwinvanhunen** [comment]
Sorry for the very long delay in processing this issue, but the fix has been merged.
