### ISSUE TITLE
Installing solutions doesn't work

### ISSUE THREAD

**Issue by hanielc** [OfficeDev/PnP-Sites-Core#14]
Hi,

I've posted this message previously in the PnP PowerShell tree but was advised to post it here instead.

Hi,

I'm trying to deploy a WSP to my Office 365 tenant using the PnP Powershell library. The manifest.xml file looks as follows:
```
<?xml version="1.0" encoding="utf-8"?>
<Solution xmlns="http://schemas.microsoft.com/sharepoint/" SolutionId="7da4b965-0514-4e14-ae87-a75618ab3e56" SharePointProductVersion="15.0">
  <Assemblies>
    <Assembly Location="Intranet.dll" DeploymentTarget="GlobalAssemblyCache" />
  </Assemblies>
  <FeatureManifests>
    <FeatureManifest Location="Intranet_.Intranet.Core\Feature.xml" />
    <FeatureManifest Location="Intranet_.Intranet.NewsSlider\Feature.xml" />
  </FeatureManifests>
</Solution>
```
When I enter the command  ```Install-SPOSolution -PackageId 7da4b965-0514-4e14-ae87-a75618ab3e56 -SourceFilePath 'Intranet.wsp'```  it returns the following error:
```
Install-SPOSolution : Invalid field name. {33e33eca-7712-4f3d-ab83-6848789fc9b6}  /sites/deptest/_catalogs/design
At line:1 char:1
+ Install-SPOSolution -PackageId 7da4b965-0514-4e14-ae87-a75618ab3e56 -SourceFileP ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Install-SPOSolution], ServerException
    + FullyQualifiedErrorId : EXCEPTION,OfficeDevPnP.PowerShell.Commands.InstallSolution
```

Where does the  ```33e33eca-7712-4f3d-ab83-6848789fc9b6```  come from? I'm able to deploy the WSP successfully via the UI.

Updates:

I've tried installing different WSP's and on different site collections and get the same error with the same GUIDs.

Thanks for all the help

**Comment by erwinvanhunen** [comment]
There is a similar issue reported: https://github.com/OfficeDev/PnP/issues/260

**Comment by VesaJuvonen** [comment]
Since issue is on the oob CSOM side, we can't fix this with PnP. Best option for now to get this natively supported would be to use user voice where we have also entry for this at https://officespdev.uservoice.com/forums/224641-general/suggestions/5633494-add-support-for-sandbox-solutions-upload-and-active. PnP CmdLets are simply using oob CSOM API to get the solution installed.

**Comment by victorcea87** [comment]
Hi, there is any solution for this problem? I have it as well
