### ISSUE TITLE
Content Type ID "0x" is not supported

### ISSUE THREAD

**Issue by lafe** [OfficeDev/PnP-Sites-Core#147]
There is an issue in the current release of the provisioing engine with regard to the Content Type ID:
The current schema specifies that the Content Type ID has to have the pattern "0x[a-zA-Z0-9]+", however the Content Type ID "0x" is valid and denotes "System": https://msdn.microsoft.com/en-us/library/office/ms452896(v=office.14).aspx (SP 2010 documentation but this hasn't changed in SP2013). The List Instance Object Handler extracts the Content Types from the list and in some cases (if the fields are assigned to the list directly), writes the "0x" Content Type ID to the output file. This makes it impossible to reimport the output file, because the Content Type ID "0x" does not match the pattern specified in the schema and therefore, a validation error occurs.

In my opinion, there are two possible fixes:
- Change the schema to allow the "System" Content Type ID ("0x")
- Change the export so that the "System" Content Type is ommited from the output

I implemented the second one to fix the issue we are currently having, but I am not sure if this is the best approach and if this might cause some side effects.

**Comment by patrick-rodgers** [comment]
Closing based on conversation in #148. Please let us know if this is still an issue, thanks!
