### ISSUE TITLE
When will 1.7.1015.1 appear as a nuget package?

### ISSUE THREAD

**Issue by cveld** [OfficeDev/PnP-Sites-Core#149]
I see that currently only 1.3.0615.0 is provided through nuget. Package name: OfficeDevPnP.Core

**Comment by VesaJuvonen** [comment]
Whenever we do master merge or bug fixing for the Core component, we also refresh or release new version of the Nuget package, since Nuget is the main distribution channel for the Core component. We update Nuget as part of the monthly master merge, which happens on first Friday of each month.
