### ISSUE TITLE
Content Type is not provisioned on List

### ISSUE THREAD

**Issue by lafe** [OfficeDev/PnP-Sites-Core#152]
We discovered that the PnP Provisioning Engine sometimes fails to add Content Types to lists. This happens if the Content Type is a derived Content Type from another Content Type and both Content Types should be assigned to the same list. In this case, the `StartsWith` method used in `FieldAndContentTypeExtensions.ContentTypeExistsById` looks at the second Content Type and sees that an already added Content Type starts with the same string. The algorithm incorrectly decides that the Content Type is already present and fails to add the second Content Type to the list.

**Comment by PaoloPia** [comment]
Hi, we have the specific PR #152 for this potential issue. Thus, I will close this one and move the thread there. Thanks.
