### ISSUE TITLE
Support for default pagelayout setting with value "__inherit"

### ISSUE THREAD

**Issue by cveld** [OfficeDev/PnP-Sites-Core#154]
When trying to export a subsite with `GetProvisioningTemplate`, this results in an exception `XmlException: Data at root level is invalid`.
```csharp
var defaultLayoutXml = web.GetPropertyBagValueString(DEFAULTPAGELAYOUT, null);
```
 results in the value `__inherit`.
And then 
```csharp
defaultPageLayoutUrl = XElement.Parse(defaultLayoutXml).Attribute("url").Value;
```
results in this exception.

Using assembly version `1.7.1015.1` of OfficeDevPnp.Core and SharePoint Server 2013 version `15.0.4753.1000`.

**Comment by SchauDK** [comment]
This is fixed in following commit https://github.com/OfficeDev/PnP-Sites-Core/commit/81a096f302c794a5547f434d82f5be9109c98bcd#diff-104ff854a76b73f401394122bb765e5d

**Comment by PaoloPia** [comment]
Thanks for your feedbacks. I will close this one.
