### ISSUE TITLE
Added option to load extra properties 

### ISSUE THREAD

**Issue by jansenbe** [OfficeDev/PnP-Sites-Core#155]
#105 is showing an interesting concept to allow core library users to dynamically control the properties that are being requested. This will result in more elegant code and better performance. 

Ask: evaluate the broader usage of this approach

**Comment by erwinvanhunen** [comment]
We have a similar functionality in PnP Core right now by means of GetProperty and the GetProperties extensions. I will close this issue.

**Comment by SchauDK** [comment]
Hi Erwin,

I'm not sure I follow. By GetProperty and GetProperties do you mean the EnsureProperty extensions?
When loading a list (or any other object for that matter), it would be nice it we could pass in the retirevals.
Sure you can call EnsureProperty or EnsureProperties afterwards, but it will cost you an extra roundtrip to the server.

**Comment by erwinvanhunen** [comment]
You're right, those where the methods I meant. I was suffering from a brainfreeze I guess :-). You're right that it could be beneficial to have this functionality, but as Bert stated in the connected PR, we will have to consider doing it throughout the framework as that makes more sense. Which is obviously quite a big task. As the issue as such does not stand, other than the feature request, I still opt to keep this issue closed. It's on our list to consider to implement (but we're restricted given time and resources and this is more a 'nice to have' than a hard requirement).
