### ISSUE TITLE
taxonomy fields only working in root web

### ISSUE THREAD

**Issue by PieterVeenstra** [OfficeDev/PnP-Sites-Core#156]
We are using a lot of taxonomy fields and we found that the field definitions for the taxonomy fields in our template.xml (used by Apply-SPOProvisioningTemplate) for our root site includes the following :

List="Lists/TaxonomyHiddenList"

For templates used by sub sites (and also exported from subsites using the PowerShell command) this is set to 
List="Guid"

Resulting in "The SPListItem being updated was not retrieved with all taxonomy fields." when we try to edit/update one of these fields.

In the root site our taxonomy fields are working but for subsites they are not.

In the subsites we then replaced the List=Guid with List="Lists/TaxonomyHiddenList" and then the taxonomy fields started working again.

So it looks like this is a problem with the export of taxonomy fields. For now we will manually replace the List=Guid lines with the correct information.  

I will do some more investigation. Is anybody else seeing the same behaviour?

**Comment by csharp01** [comment]
I'm facing a similar problem. The value of the MMProperty owstaxId<FieldInternalName> is empty in search results. I also has an RefinableString mapped to the field ows_TestMultiTaxField and this one works, but not whole taxonomy filed including the guid and allt that stuff.

owstaxIdTestMultiTaxField: <empty>
RefinableString00:  Test term label

I'm not sure if this issue is related to a bug i the PnP Site Provisioning (I'm using the 201508 schema). I have created tax.fields using CSOM and PnP extensions that are working for tree month ago. Or some updates in SP Online has now made all new tax.fields is not working any more.

**Comment by csharp01** [comment]
I'm working on a case with Microsoft on this (I could not recevie values from the auto created MM type  owstaxId MyField)
There is several issues here so if are not provisioning the taxonomy fiels correct it will be broken and the crawler will not pick the whole field value of the term/terms.

When using the Site Provisioning Schem the taxonomy fields was not created correct. I have not found so much information of how to use the 201508 schema and taxonomy fields, but one way I did find was to specify both fields. The hidden Note field and the TaxonomyFieldType field with all properties specified in the schema, including the reference to the Note field. This one was not working.
I have also created taxonomy fields through PnP Core the scheam and this one seams to work well,

Another issue is that new recomendation is to alwasy map the ows_taxId_YourField Name to RefinableString... (tenant level or site collection level) instead to use the auto created owstaxId YourField. There is some issues with multivalue fields that MS are working on. I'm not sure exactly what they changing by was told to use RefinableString... in the future when I need to make complex queries based on the guid and full field value.

**Comment by Pieter-Veenstra** [comment]
When I apply taxonomy fields to a sub site (=not root site) my taxonomy fields tend to break. The only way to fix them is to apply a template to the root site. I'm copying between tenants and therefore my taxonomyhidden list Guid will be different.

When I export a template from  a root site tokens like {listid:taxonomyHiddenList} are added to point towards the right taxonomy list. 

The following code in the Tokenize method is responsible for this:

            var lists = web.Lists;
            foreach (var list in lists)
            {
                xml = Regex.Replace(xml, list.Id.ToString(), string.Format("{{listid:{0}}}", list.Title), RegexOptions.IgnoreCase);
            }

However this fails for sub sites as web is the sub site and the list lives in the rootweb. Lists like the TaxonomyHiddenList need to be looked at for sub sites too. so just looking  at the sub web will not be the right solution.

**Comment by erwinvanhunen** [comment]
Hi Pieter,

We changed the way listid tokens are being resolved a few releases ago, and the listid:taxonomyHiddenList token should resolve correctly now even when on a subweb. If this issue is still present, do not hesitate to reopen it, but for now I will close it.
