### ISSUE TITLE
SetDefaultColumnValues generates multiple A tags with same location in client_LocationBasedDefaults.html

### ISSUE THREAD

**Issue by jeroenvanlieshout** [OfficeDev/PnP-Sites-Core#163]
I'm using the SetDefaultColumnValues extension method to set default metadata on some fields when provisioning sites using the Framework by invoking a custom provider which hooks in the provisioning process. However I see weird outcomes when setting default metadata on libraries. Some default values are not set as expected (few columns get default values, others not). After investigating I found out that something is messing up the anchortags in the client_LocationBasedDefaults.html form which is set up by the PnP extension method. 

Example of XML outcome in client_LocationBasedDefaults.html:
```xml
<MetadataDefaults>
  <a href="/sites/PROJECT/SUBSITE/SUBSITE/LIBRARY">
    <DefaultValue FieldName="Field1">1;#Value1|38285471-58c3-47a7-88f1-78af509c2b17</DefaultValue>
    <DefaultValue FieldName="Field2">2;#Value2|a96363e7-7c7a-4070-b8d7-ad9fd4261d3e</DefaultValue>
    <DefaultValue FieldName="Field3">3;#Value3|27e1ed51-21fd-4892-9803-136a28bff8a0</DefaultValue>
  </a>
  <a href="/sites/PROJECT/SUBSITE/SUBSITE/LIBRARY">
    <DefaultValue FieldName="Field1">1;#Value1|38285471-58c3-47a7-88f1-78af509c2b17</DefaultValue>
    <DefaultValue FieldName="Field2">2;#Value2|a96363e7-7c7a-4070-b8d7-ad9fd4261d3e</DefaultValue>
  </a>
  <a href="/sites/PROJECT/SUBSITE/SUBSITE/LIBRARY">
    <DefaultValue FieldName="Field1">1;#Value1|38285471-58c3-47a7-88f1-78af509c2b17</DefaultValue>
    <DefaultValue FieldName="Field2">2;#Value2|a96363e7-7c7a-4070-b8d7-ad9fd4261d3e</DefaultValue>
    <DefaultValue FieldName="Field3">3;#Value3|27e1ed51-21fd-4892-9803-136a28bff8a0</DefaultValue>
  </a>
</MetadataDefaults>
```

The clue is that the path of all these default values is the same. According to the code in Core/OfficeDevPnP.Core/AppModelExtensions/ListExtensions.cs in the method SetDefaultColumnValuesImplementation (line 1015) the code is filling the xATag variable. But I see that this variable is in each iteration adding itself to the xMetadataDefaults element (line 1080). This should be done once per location iteration, instead of doing this every time. This line should be moved after line 1083 (note: Line numbers based on Dev branch). Tested this myself using a copy of the code and then the outcome looks like this:

```xml
<MetadataDefaults>
  <a href="/sites/PROJECT/SUBSITE/SUBSITE/LIBRARY">
    <DefaultValue FieldName="Field1">1;#Value1|38285471-58c3-47a7-88f1-78af509c2b17</DefaultValue>
    <DefaultValue FieldName="Field2">2;#Value2|a96363e7-7c7a-4070-b8d7-ad9fd4261d3e</DefaultValue>
    <DefaultValue FieldName="Field3">3;#Value3|27e1ed51-21fd-4892-9803-136a28bff8a0</DefaultValue>
  </a>
</MetadataDefaults>
```

I've tested this and this also gives the expected outcome. I compared this with the result when setting the values manually by using the UI. The outcome is exactly the same. Can this be fixed in the next release, such that the SetDefaultColumnValues method works as expected?

**Comment by bcage29** [comment]
+1 I'm seeing the same issue and came to the same conclusion. The one line of code needs to be outside of the foreach loop (line 1084) in ListExtensions.cs

![xmedadatadefaults](https://cloud.githubusercontent.com/assets/13458224/12798333/6d2bff72-ca8e-11e5-818b-581b35068df3.JPG)

@VesaJuvonen

**Comment by erwinvanhunen** [comment]
Sorry for the very long delay. The fix has been merged now.
