### ISSUE TITLE
Stub for the type with id "..." not found

### ISSUE THREAD

**Issue by cveld** [OfficeDev/PnP-Sites-Core#168]
I get an exception through `web.Client.ExecuteQuery()` when I try to extract a provision template with `GetProvisioningTemplate`. I diagnosed with a couple of extra `ExecuteQuery` here and there and the problem appears within ObjectContentType.cs `GetEntities`. At the start of the method I get no exception and at the end of the method I do get the exception. Maybe it is due the `FieldLinks` not loading properly?

The exact id in the exception is `{1554af8c-7213-418c-a4a8-b06e7603c68a}`.

I am using SharePoint server version 15.0.4569.1000.

**Comment by PaoloPia** [comment]
Hi, thanks for your feedback. Are you still experiencing the described issue? Otherwise, I will close this item. Thanks.

**Comment by erwinvanhunen** [comment]
I will close this issue as thread seems dead.
