### ISSUE TITLE
Content Type column order incorrect

### ISSUE THREAD

**Issue by lafe** [OfficeDev/PnP-Sites-Core#174]
When using the Provisioning engine, it is possible that the column order of a provisioned Content Type is wrong.
If a Content Type (CT-B) extends a different Content Type (CT-A), the Provisioning Engine creates CT-A first. Afterwards, it creates CT-B that referecnes CT-A. Because of this parent-child-relationship, all columns from CT-A are immediately present in CT-B in the order that is specified in CT-A. While adding the columns to CT-B, the engine skips the columns already present and only adds the columns that are unique to CT-B. These columns will be added after the already created columns.

**Comment by PaoloPia** [comment]
Hi,
Because the referenced fix has been merged, I will close this issue. Thanks.
