### ISSUE TITLE
UserCustomAction ignores sequence on ScriptLink

### ISSUE THREAD

**Issue by Trickass** [OfficeDev/PnP-Sites-Core#177]
When creating a CustomAction with location *ScriptLink*, the *Sequence* property is ignored.
Could you please change this?

The relevant code is located in *AddCustomActionImplementation* method in *NavigationExtensions.cs*.

**Comment by PaoloPia** [comment]
Hi, 
Thanks for your feedback. This one should be fixed. I will close the issue.
