### ISSUE TITLE
Get-SPOProvisioningTemplate  ComposedLook

### ISSUE THREAD

**Issue by PieterVeenstra** [OfficeDev/PnP-Sites-Core#178]
Hi 

When I export site with Get-SPOProvisioningTemplate I'm getting an xml with the following included:

< pnp:ComposedLook Name="Office" ColorFile="" FontFile="" BackgroundFile="" MasterPage="{masterpagecatalog}/seattle.master" SiteLogo="{site}Style%20Library{site}bluesource{site}logo_block.png" AlternateCSS="{site}Style Library{site}bluesource{site}bluesource.css" Version="0" />

all the {site} should be replaced with '/'

When applying the template with the above line Apply-SPOProvisioningTemplate  will generate an error.

After correcting the line to the following all works fine.

< pnp:ComposedLook Name="Office" ColorFile="" FontFile="" BackgroundFile="" MasterPage="{masterpagecatalog}/seattle.master" SiteLogo="/Style%20Library/bluesource/logo_block.png" AlternateCSS="/Style Library/bluesource/bluesource.css" Version="0" />

**Comment by erwinvanhunen** [comment]
Hi Pieter,

For my understanding: you're using the latest and greatest build of the engine? E.g. the November release? 

Are you extracting the template from a rootsite? e.g. https://yourserver.sharepoint.com

**Comment by PieterVeenstra** [comment]
Hi Erwin,
I was using the dev branch from a few days ago.
I just tried the November release and that doesn't seem  to export Composed looks at all.

Yes, I'm exporting the root web.  So after the connect I'm running *Get-SPOProvisioningTemplate -Out C:\Temp\test.xml**

**Comment by erwinvanhunen** [comment]
Okay, I checked the code and this issue occurs specifically when you are exporting the rootsite, due to the way we tokenize the URLs. I will work on a fix for that one.

Regarding the not seeing any composed look at all when using the latest November release, that's a bit puzzling, and right now, the dev branch did not really change since the November release (as the dev branch was merged into the master branch, which in turn is the November release).

**Comment by erwinvanhunen** [comment]
actually, we didn't do any serious changes to the dev branch since the November release. E.g. the dev branch = the November release. Interesting that you don't get any composed look exported at all...

**Comment by PieterVeenstra** [comment]
Just to clear things up. My dev branch used code from just before the November release . I think that I picked up the code about 2 or 3 days before I saw the release email alerts. I assumed that dev would turn into the next release and therefore didn't bother 'upgrading'

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. In the latest months we heavily updated the inner logic of the engine about handling Compose Looks. I guess that this issue should be solved and I will close this item. If that is not the case, please let us know and I will re-open it. Thanks.
