### ISSUE TITLE
Custom Action Handler doesn't update the Sequence

### ISSUE THREAD

**Issue by luismanez** [OfficeDev/PnP-Sites-Core#187]
Related with issue #177 I've also found that the Sequence property is not updated when you re-apply the template with the same Custom Action.
I am about to do a Pull Request to fix this bug, also including the change that @Trickass has done in the PR #186 (just in case), but please, note that all the credit about the fix to set the Sequence is for @Trickass

**Comment by erwinvanhunen** [comment]
fixed through PR #189
