### ISSUE TITLE
ListInstance object handler doesn't update Versioning settings on default Pages library

### ISSUE THREAD

**Issue by luismanez** [OfficeDev/PnP-Sites-Core#193]
If you set a ListInstance node in the template XML pointing to the Default Pages library (publishing), some versioning features are not updated. This is because in the UpdateList method, it does:

if (existingList.BaseTemplate == (int)ListTemplateType.DocumentLibrary)

However, Page lib BaseTemplate is 850, and not 101.

I think it could be fixed changing the If as:

if (existingList.BaseType == BaseType.DocumentLibrary)

I've tested it with the Pages library and works fine. Not sure if I'm missing other scenarios.
I'm going to do a new PR to fix it that way, and see what the PnP team say.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. Because the fix (PR #194) has been merged, I will close this one.
