### ISSUE TITLE
{listid:<name>} issue in list view webpart

### ISSUE THREAD

**Issue by krunal039** [OfficeDev/PnP-Sites-Core#198]
We are trying to add listview webpart with PnP file module with <pnp:webpart> <pnp:Contents> <![CDATA[]]></pnp:Content></pnp:webpart>, CDATA include .webpart file content exported from site and it required listid and we have used below line to resolve listid but pnp provisioning engine does not resolve listid.

 <property name="ListId" type="System.Guid, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">{listid:QuickLinks}</property>

Is it know issue or token is not supported in webpart content.

**Comment by erwinvanhunen** [comment]
It is not a known issue, and the token _is_ supported. Thank you for reporting this.

The list in question, e.g. the one you are referring to with the token, is it present in the site or is it part of the template you're provisioning?

**Comment by krunal039** [comment]
Thanks for quick reply it is already present in site and deployed through pnp:listinstance before it is trying to add list viewwebpart to pagelayout.

I have below error.

There is an error occured : List View Web Part could not be added, list may be hidden.

**Comment by krunal039** [comment]
It was caused by out visual studio deployment configuration and token was replaced correctly just build system issue so not actual PnP issue so I am closing it now. Thanks for Erwin for quick help.
