### ISSUE TITLE
Importing Workflows

### ISSUE THREAD

**Issue by PieterVeenstra** [OfficeDev/PnP-Sites-Core#204]
Exporting SharePoint designer workflows seems to be working. Importing workflows however gives me:

Apply-SPOProvisioningTemplate : Value cannot be null.
 Parameter name: input

Is this a known issue or am I doing something wrong?

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. The import phase should work, as long as you don't reference other lists in the workflow (we're aware of a bug in that scenario, which is planned to be fixed ...). Are you still experiencing this issue? Thanks.

**Comment by PieterVeenstra** [comment]
Hi Paola,

I have just tried this with the latest code and I'm still getting the same error.

I will do some investigation into this problem.

**Comment by PieterVeenstra** [comment]
I got a bit further however I'm getting timouts on the workflow services now. If this was an onpremises environment then this would likely be the Workflow Manager services that need starting. This is a workflow running in Office 365 

[ERROR] Apply-SPOProvisioningTemplate : System.TimeoutException: The HTTP request has timed out 
[ERROR] after 200000 milliseconds. ---> System.Net.WebException: The request was aborted: The 
[ERROR] request was canceled.
[ERROR]    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
[ERROR]    at Microsoft.Workflow.Client.HttpGetResponseAsyncResult`1.OnGotResponse(IAsyncResult

**Comment by PieterVeenstra** [comment]
Please ignore the above. Microsoft engineers have fixed the timeout. The message center got a warning as soon as I started getting these time outs.

**Comment by SimonPurr** [comment]
Hi, I am getting this error when using the PowerShell commands, not sure what the issue is here?

Apply-SPOProvisioningTemplate -Path C:\TempXML\template.xml -Web $web  -ResourceFolder C:\TempXML


Apply-SPOProvisioningTemplate : Value cannot be null.
Parameter name: stream
At line:5 char:1
 Apply-SPOProvisioningTemplate -Path C:\TempXML\template.xml -Web $web ...
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CategoryInfo          : WriteError: (:) [Apply-SPOProvisioningTemplate], ArgumentNullException
    FullyQualifiedErrorId : EXCEPTION,OfficeDevPnP.PowerShell.Commands.Branding.ApplyProvisioningTemplate

**Comment by ntinykumar** [comment]
Apply-SPOProvisioningTemplate -Path C:\TempXML\template.xml -Web $web -ResourceFolder C:\TempXML

Apply-SPOProvisioningTemplate : Value cannot be null.
Parameter name: stream
At line:5 char:1
Apply-SPOProvisioningTemplate -Path C:\TempXML\template.xml -Web $web ...


I get the same error. How to resolve it ?
