### ISSUE TITLE
SetDefaultColumnValues sets SPEventReceiver with wrong Synchronization property

### ISSUE THREAD

**Issue by jeroenvanlieshout** [OfficeDev/PnP-Sites-Core#211]
When using SetDefaultColumnValues this gives issue when working with folders or document sets. On document sets and folders my default values are not set when uploading a new document, while it works when doing it directly on the library. So I started to configure it on a plain site without using PnP Provisioning and performing the configuration manually. Then I found out that there is a difference in the configuration of the LocationBasedMetadataDefaultsReceiver ItemAdded eventreceiver. On the PnP configured site the Synchronization property is set to DefaultSynchronization in code, which results in Asynchronous on my library:
![image](https://cloud.githubusercontent.com/assets/13566988/11367093/b48b52ba-92b1-11e5-8eae-87e23f60f415.png)

I compared this value with the value of the library which has been manually configured and found out that this one is set to Synchronous:
![image](https://cloud.githubusercontent.com/assets/13566988/11367164/35527edc-92b2-11e5-826a-e473c817468d.png)

After setting the eventreceivers on the other list as well to Synchronous my issue with default values on document sets and folders has been disappeared. Can this be changed in the code such that the eventreceiver works the same as when configuring the default values using the UI?

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We fixed the issue with PR #399.
