### ISSUE TITLE
Provisioning Engine - Created document libraries are missing the "Folder" content type

### ISSUE THREAD

**Issue by artokai** [OfficeDev/PnP-Sites-Core#212]
If the provisioning template has the "Remove Existing Content Types" -flag set for a document library, the provisioning engine will also remove the Folder content type from the created list.

This content type is hidden from the users in the SharePoint UI, but for example OneDrive sync needs this content type to be present in order to work. Therefore it would be best if the provisioning engine would never delete this content type even if the "Remove Existing Content Types" -flag is set.

I will submit a PR for this.

**Comment by VesaJuvonen** [comment]
Fixed merged to core component. Thx Arto for this.
