### ISSUE TITLE
Provision Engine: Unique permissions are set on objects while no ObjectSecurity is set in XML

### ISSUE THREAD

**Issue by jeroenvanlieshout** [OfficeDev/PnP-Sites-Core#216]
When not specifying ObjectSecurity for example for DataRows, Pages, etc the items get by default unique permissions. This is unexpected behavior as you don't expect broken permissions when not specifying explicitly to break permissions on specific objects.

This is caused by the fact that the checks on the security objects are incorrect for at least DataRows and Pages. There is only a null check performed, but by default the Security object is always instantiated causing the SetSecurity method to be called. Sample of security handling for DataRow:
```c#
if (dataRow.Security != null) 
{ 
    listitem.SetSecurity(parser, dataRow.Security); 
} 
```
In the SetSecurity method the securable object automatically gets broken permissions by the BreakRoleInheritance method. So there is never any check done that there are actually any roleassignments specified before breaking the inheritance.
```c#
public static void SetSecurity(this SecurableObject securable, TokenParser parser, ObjectSecurity security)
{
    //using (var scope = new PnPMonitoredScope("Set Security"))
    //{
           var context = securable.Context as ClientContext;

            var groups = context.LoadQuery(context.Web.SiteGroups.Include(g => g.LoginName));
            var webRoleDefinitions = context.LoadQuery(context.Web.RoleDefinitions);

            context.ExecuteQueryRetry();

            securable.BreakRoleInheritance(security.CopyRoleAssignments, security.ClearSubscopes);
            // more code below
}
````

I think a check should be built in that nothing is done with permissions when there is no ObjectSecurity is supplied in the XML scheme.

**Comment by jeroenvanlieshout** [comment]
#200

**Comment by luismanez** [comment]
I think this is fixed in PR #209 by @olemp
take a look to the code he's done, but I think will fix your case too.

**Comment by jeroenvanlieshout** [comment]
Thnx luismanez. This will indeed fix the issue. I will close my bug then as this will be fixed in the next release.

**Comment by luismanez** [comment]
no worries! that reminds me I can close mine as well :)

**Comment by olemp** [comment]
Good job guys :) My PR has been open for 3 days now. We'll see if they have time to go through it next week! :+1:
