### ISSUE TITLE
Folder Structure isn't being recreated

### ISSUE THREAD

**Issue by adameska** [OfficeDev/PnP-Sites-Core#217]
When I set EnableFolderCreation to true it's not re-creating the folder structure from the old list into the new site template. Is there anyway to persist folders inside a site list?

**Comment by adameska** [comment]
I was able to get this working by adding a new property to the SiteTemplateCreateInfo called PersistFolderStructure and then modifying the list instance code to apply them based on this setting and if folders existed. Everything seems to work, let me know if you want me to upload the code.

**Comment by PaoloPia** [comment]
Thanks for your feedbacks. We introduced folders support in the last months. I will close this one.
