### ISSUE TITLE
Allow for multilevel xi:Include

### ISSUE THREAD

**Issue by olemp** [OfficeDev/PnP-Sites-Core#218]
Allow for multilevel xi:Include to support dividing very large files.

Very handy in Files or Pages.xml where you have loads of Pages/Files with webparts.

Not sure where this belongs. Also posted under PnP-Provisioning-Schema:

https://github.com/OfficeDev/PnP-Provisioning-Schema/issues/50

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We already support multiple x:include elements in the PnP Provisioning Engine. Do you mean recursive x:include elements? Thanks.

**Comment by olemp** [comment]
Oh, sorry! I mean recursive for sure :)
