### ISSUE TITLE
Allow for recursive xi:Include

### ISSUE THREAD

**Issue by olemp** [OfficeDev/PnP-Sites-Core#220]
Allow for recursive xi:Include to support dividing very large files.

Template.xml => xi:include Files.xml => xi.include => SearchWebPart1.xml

Very handy in Files or Pages.xml where you have loads of Pages/Files with webparts.

**Comment by ozmav** [comment]
This has been in place since about the November 2015 release. XMLTemplateProvider.cs -> ResolveXIncludes;

**Comment by olemp** [comment]
@ozmav Recursive?

**Comment by PaoloPia** [comment]
Hi, thanks for your feedbacks. Yes, there is support for recursive XIncludes. Have a look here (https://github.com/OfficeDev/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/XMLTemplateProvider.cs#L230). I will close this issue.
