### ISSUE TITLE
Pages are not extracted

### ISSUE THREAD

**Issue by cveld** [OfficeDev/PnP-Sites-Core#241]
ObjectPages.ExtractObjects currently does not extract pages. It would be nice if we can add this functionality.

**Comment by PaoloPia** [comment]
Hi, thanks for your feedback. Unfortunately we do not support pages extraction and there are no plans to do that on the roadmap, in order to avoid creating a content migration tool, instead of a provisioning tool. I will close this one.

**Comment by cveld** [comment]
I believe there is a grey area where site templating should also encompass some content such as pages and other list and library content.
