### ISSUE TITLE
Navigation Object Handlers

### ISSUE THREAD

**Issue by olemp** [OfficeDev/PnP-Sites-Core#261]
Navigation Object Handlers for Global and Local Navigation would be very nice.

Example:
```
<pnp:Navigation>
<pnp:GlobalNavigation>
<pnp:NavigationNode Title="" Url="" />
<pnp:NavigationNode Title="" Url="" />
<pnp:NavigationNode Title="" Url="" />
</pnp:GlobalNavigation>
<pnp:LocalNavigation>
<pnp:NavigationNode Title="" Url="" />
<pnp:NavigationNode Title="" Url="" />
<pnp:NavigationNode Title="" Url="">
<pnp:ChildrenNodes>
<pnp:NavigationNode Title="" Url="" />
<pnp:NavigationNode Title="" Url="">
</pnp:ChildrenNodes>
</pnp:NavigationNode>
</pnp:LocalNavigation>
</pnp:Navigation>
```

**Comment by PaoloPia** [comment]
Hi Ole,
Thanks for your feedback. Sometime we thought about this potential new feature. However, we should also carry the pages (i.e. the contents) referenced within the navigation links. Right now, we don't want to make the PnP Provisioning Engine become a content migration tool. Thus, we will not implement it. Maybe we will make a pluggable external provider for that, in the future. Thanks.
