### ISSUE TITLE
Error occurred when calling Web.GetPublishingPage method on non English sites

### ISSUE THREAD

**Issue by iceear** [OfficeDev/PnP-Sites-Core#265]
The following code is the implementation of the Web.GetPublishingPage(...) extension method, seems the resource id used is not quite appropriate. The returned **List_Pages_UrlName** is always in English, but for other languages, the Pages list title could be a different non English string. That will cause **GetByTitle(...)** throw an exception.

    ClientResult<string> pagesLibraryName = Utility.GetLocalizedString(context, "$Resources:List_Pages_UrlName", "cmscore", (int)web.Language);
    context.ExecuteQueryRetry();

    List spList = web.Lists.GetByTitle(pagesLibraryName.Value);
    context.Load(spList);
    context.ExecuteQueryRetry();

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback.  This issue has been fixed. I will close this.
