### ISSUE TITLE
Dev - provisioningInfo is set to null 

### ISSUE THREAD

**Issue by PieterVeenstra** [OfficeDev/PnP-Sites-Core#267]
Within the current dev branch I'm getting problems when provisioningInfo is set to null in SiteToTemplateConversion. Should the if block go around the objectHandler.Add section?

if (provisioningInfo != null) 
121                 { 
122                   .....
136                 } 
137 
 
.... 
140                 if (provisioningInfo.HandlersToProcess.HasFlag(Handlers.RegionalSettings)) objectHandlers.Add(new ObjectRegionalSettings()); 
141                 if (provisioningInfo.HandlersToProcess.HasFlag(Handlers.SupportedUILanguages)) objectHandlers.Add(new ObjectSupportedUILanguages()); 
142

**Comment by PaoloPia** [comment]
Hi Pieter,
Thanks for your contribution! This has been fixed in February release. I will close the issue.
