### ISSUE TITLE
AlternateCssUrl File is downloaded but  file entries is not created

### ISSUE THREAD

**Issue by Bestadd** [OfficeDev/PnP-Sites-Core#277]
In ObjectComposedLook SiteLogoUrl, BackgroundFile, ColorFile, and FontFile are all downloaded then have File entities created and added to the template.  AlternateCssUrl does not.  Is there a reason for this?

**Comment by Bestadd** [comment]
this may only be an insure in the current release.  I was reviewing the code in the dev branch and object handlers have change significantly.  I'm going to try the dev branch and see if this is solved, report back soon.

**Comment by Bestadd** [comment]
Using the dev or master branch with the Debug15 profile the AlternateCssUrl is set but the file it references is not downloaded and is not referenced in the Files section.  I propose that this be changed so regardless of 15/16 code base if the AlternateCssUrl  references a file in the current site it be downloaded and included as a file in the template. 

I would make the change and submit it myself but I'm working though some IP issues with my work.  So for now this is the best I can do.

**Comment by PaoloPia** [comment]
Hi Bestadd,
Thanks for your contribution. We will make it possible to download the CSS file, if the PersistBrandingFiles flag is set to true, and if the CSS is within the same site that you are exporting the template from. I will let you know when it is done. Thanks.

**Comment by PaoloPia** [comment]
Hi Bestadd, 
I just realized that it is already implemented, since Jan 2016. I will close this Issue, but feel free to let us know in case of any further need. Thanks.
