### ISSUE TITLE
Apply-SPOProvisioningTemplate with just Term groups / Term Sets / Terms fails Index out of Range

### ISSUE THREAD

**Issue by NPrice99** [OfficeDev/PnP-Sites-Core#29]
Hi
If I use Apply-SPOProvisioningTemplate with a Template containing Term groups / Term Sets / Terms fails with Index Out of Range.

If I rerun the command, It gets a little further and fails with Index Out of Range again.

Regards

Nigel

**Comment by NPrice99** [comment]
Full error "Specified argument was out of the range of valid values."

**Comment by NPrice99** [comment]
This works with the pre-August 2015 master release

**Comment by NPrice99** [comment]
I have run this again and If I have a brand new site and run the script it works fine.  No issues.  If run the script again over the same site, I get the error "Index Out Of Range" error.  I have now tried this with a couple of different templates and sites.

**Comment by PaoloPia** [comment]
Hi Nigel, is this issue still open for you? We made a bunch of fixes in the latest three months and I guess it should be fixed. Please let me know, otherwise I will close it. Thanks.

**Comment by NPrice99** [comment]
Fixed 18/02/2016

**Comment by NPrice99** [comment]
Hi Paolo

I have closed this one as fixed.

Regards

Nigel

Using Windows 10

**Comment by PaoloPia** [comment]
Thanks!
