### ISSUE TITLE
Apply-SPOProvisioningTemplate fails with August Master but works with July Dev

### ISSUE THREAD

**Issue by NPrice99** [OfficeDev/PnP-Sites-Core#31]
Hi
If I run a Provisioning Template which was created in July (middle of) and worked without a hitch at the end of July, now fails with illegal field name with a GUID which corresponds to the SEOBrowserTitle field which is a standard Publishing Column with a display name of "Browser Title" whilst creating a Content Type.  So the failure was a FieldRef inside the Content Type Definition in the Provisioning Template.  I was running the on-premises PowerShell Command Apply-SPOProvisioningTemplate from the Master branch of the August Release when the failure occurred.  The actual error was Apply-SPOProvisioningTemplate : Invalid field name. {ff92f929-d18b-46d4-9879-521378c689ef} 

The OfficeDevPnP.core.dll which worked (and still works) was version 1.4.0815 - created on the 7th july at 21:16:24 and modified on the 28th July at 20:50.23.

Any ideas why this is happening ?

Regards

Nigel

**Comment by PaoloPia** [comment]
Hi Nigel, is this one still open? Thanks.

**Comment by NPrice99** [comment]
Hi Paolo

I updated my PnP stuff last night I will check to see if this and the other bug has been fixed tonight

Regards

Nigel

**Comment by NPrice99** [comment]
Fixed 18/02/2016

**Comment by NPrice99** [comment]
Hi Paolo

I will  close this one.

Regards

Nige

**Comment by PaoloPia** [comment]
Thanks!
