### ISSUE TITLE
MailUtility - Infinite loop in SendEmail

### ISSUE THREAD

**Issue by evaneenwyk** [OfficeDev/PnP-Sites-Core#311]
The helper function for sending email (SendEmail) that converts a plain text password into a SecurePassword is stuck in an infinite loop due to the fact that it is passing the wrong parameter into the SendEmail (plain text again versus a SecurePassword).

        public static void SendEmail(string servername, string fromAddress, string fromUserPassword, IEnumerable<String> to, IEnumerable<String> cc, string subject, string body, bool sendAsync = false, object asyncUserToken = null)
        {
            // Get the secure password
            var secureString = new SecureString();
            foreach (char c in fromUserPassword.ToCharArray())
            {
                secureString.AppendChar(c);
            }

            SendEmail(servername, fromAddress, <<INCORRECT>fromUserPassword<<INCORRECT>>, to, cc, subject, body, sendAsync, asyncUserToken);
        }

**Comment by erwinvanhunen** [comment]
Good catch!

**Comment by erwinvanhunen** [comment]
Fixed in PR #312 . Closing this issue.
