### ISSUE TITLE
Provisioning Engine - List Schema should support specifying the checkout required property

### ISSUE THREAD

**Issue by patrick-rodgers** [OfficeDev/PnP-Sites-Core#339]
[This was originally reported in the core and missed during the transition.](https://github.com/OfficeDev/PnP/issues/1099)

The List schema of the provisioning engine does not support specifying the "Require documents to be checked out before they can be edited" property (ForceCheckout property). It will be nice to be able to specify this property via the mark up.

**Comment by PaoloPia** [comment]
I've created an issue in the PnP-Provisioning-Schema repo so that we can update the schema (first) and the engine (after).

**Comment by PaoloPia** [comment]
Added with schema 201605.
