### ISSUE TITLE
List items not included in exported template

### ISSUE THREAD

**Issue by spcfran** [OfficeDev/PnP-Sites-Core#349]
When generating a template, `<DataRows>` are not extracted. The `ObjectListInstanceDataRows.ExtractObjects` method is in fact empty:
https://github.com/OfficeDev/PnP-Sites-Core/blob/dev/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectListInstanceDataRows.cs#L161

Is there any design/architectural reason behind this, or just nobody has implemented it yet? Happy to give it a go if the latter

**Comment by jansenbe** [comment]
We've made a deliberate choice to not export content except for the home page of a site...we don't want to get into building a migration tool :-)

Anyhow, you can always write your own extensibility provider and implement the code in there.

**Comment by heinrich-ulbricht** [comment]
Side note: list data can (nowadays?) be added to the template using `Add-PnPDataRowsToProvisioningTemplate`
