### ISSUE TITLE
Provisioning template generator does not create "<Feature deactivate=" 

### ISSUE THREAD

**Issue by LenCardinal** [OfficeDev/PnP-Sites-Core#353]
The provisioning template generator does not create "<Feature deactivate=" entries.  These can be manually added to the XML file, but that has its own concerns from a maintenance perspective.

**Comment by erwinvanhunen** [comment]
It's correct that it does not do that. With CSOM it is only possibly to retrieve active features from a site, e.g. there is no way for us to figure out what features have not been activated and as a result we cannot generate <Feature Deactivate=""> entries.
