### ISSUE TITLE
Lookup column creation in site provisioning engine

### ISSUE THREAD

**Issue by srirams007** [OfficeDev/PnP-Sites-Core#360]
During the save site as template, the lookup column generated with {ListId:Listname}. This is not working expected. Developer needs to the change lookup column mapping with Lists/Listname in the xml, then its working as expected.

**Comment by PaoloPia** [comment]
Hi, 
Thanks for your feedback. Are you referring to the "Save Site as Provisioning Template" capability that we provide with the PnP Partner Pack? Thanks.

**Comment by srirams007** [comment]
Yes, We started fixing this issue.

**Comment by PaoloPia** [comment]
Ok, great. I'm looking forward to see the PR. Thanks.

**Comment by srirams007** [comment]
Fixed the issue in the dev branch. Please verify and merge this to master branch.
