### ISSUE TITLE
Engine always returns subsite as  true for the  the root site collection

### ISSUE THREAD

**Issue by srirams007** [OfficeDev/PnP-Sites-Core#362]
During the site column creation, observed that IsSubsite method returns always true. because of this, couldn't able to create site columns.

**Comment by PaoloPia** [comment]
Hi,
Thanks for your feedback. We recently found a bug related to the IsSubSite method, and we fixed it. Please double-check your issue. I will close this one, but please let us know if you are still experiencing any issue. Thanks.
