### ISSUE TITLE
SharePoint designer workflow - issue with site provisioning engine

### ISSUE THREAD

**Issue by srirams007** [OfficeDev/PnP-Sites-Core#364]
I have created a SP designer workflow. "Save as Site Provisioning template". site has provisioned successfully, but when I open the SharePoint designer workflow in the provisioned site, workflow UI doesn't able to retrieve the appropriate task list (i.e. workflow tasks). it shown some GUID instead of the task name/list name.

**Comment by PaoloPia** [comment]
Hi Srirams007,
This one should be fixed. Could you please try it again and let us know? In the meantime I will close the issue. Feel free to re-open it, in case you still experience the issue even using the latest DEV build. Thanks.
