### ISSUE TITLE
PageLayout WebApplicationUrl detection not working for HostNamed webApp

### ISSUE THREAD

**Issue by CedricOettel** [OfficeDev/PnP-Sites-Core#366]
Hello @jansenbe and @PaoloPia ,

I wondered, why the following line does not Export layout files for on-premise:
`Get-SPOProvisioningTemplate -Out "..." -Handler Publishing -PersistPublishingFiles`

The method GetWebApplicationUrl ( [ObjectPublishing](https://github.com/OfficeDev/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectPublishing.cs) ) does not work for URLs like:
 
- http://internet.contoso.com
- http://internet.contoso.com/subweb

Extracting from Sub-Sitecollection like http://internet.contoso.com/sites/TeamSitecollecitonA works for on-premise. The Regex usage seems to be unstable for recognition.

**Comment by CedricOettel** [comment]
When the PageLayouts are extracted, they are stored like:
`<pnp:PageLayouts Default="_catalogs/masterpage/MyPageLayout.aspx>
   <pnp:PageLayout Path="_catalogs/masterpage/MyPageLayout.aspx" />
</pnp:PageLayouts`

The method SetAvailablePageLayouts throws an error, because it cannot find that PageLayout and method CreateXmlNodeFromPageLayout does not check if the retrieved object is null.

Manually changing the path to the following, works for apply-SPOProvisioningTemplate on a SubWeb
`<pnp:PageLayouts Default="MyPageLayout.aspx>
   <pnp:PageLayout Path="MyPageLayout.aspx" />
</pnp:PageLayouts`

I think it's because the SetAvailablePageLayout method is always expecting to search files that are in the RootWeb's MasterPage gallery.
So changing the extraction logic to get only the filenames would fix this.

**Comment by CedricOettel** [comment]
WebSettings WelcomePage also extracts wrong tokenization:
`<pnp:WebSettings WelcomePage="Pages{site}Default.aspx" ... />`

**Comment by PaoloPia** [comment]
Hi Cedric,
Thanks for your feedbacks. Are all of your issues relate to the root site collection of a web application? On-premises or in SPO? Thanks.

**Comment by CedricOettel** [comment]
Yes all for root site collection of web application, running On-Prem. 
The Regex for ObjectPublishing.GetWebapplicationUrl is not working for all of These Scenarios. The regex only works for Sub - site collections.
The method "GetWebApplicationUrl" should be added to the unit tests, to test all possible URL structures.

**Comment by PaoloPia** [comment]
Hi Cedric,
we should have fixed these issues. The fixes are in the DEV branch. I will close this issue. Thanks for your support.
