### ISSUE TITLE
Provisioning engine does not implement library versioning setting

### ISSUE THREAD

**Issue by LenCardinal** [OfficeDev/PnP-Sites-Core#374]
The provisioning template generator does not seem to apply library versioning settings. in a template where a document library's where the maximum number of major versions was set to 10 using attribute `MaxVersionLimit="10"`, the library's versioning settings remained at default values after applying the template.

**Comment by rfjschouten** [comment]
I see the same happen when you try to update the OOB Shared Documents library from a template. Seems like the settings are not updated.

**Comment by erwinvanhunen** [comment]
I just checked with the latest dev branch and I am not able anymore to reproduce this issue. I will close this issue, but do not hesitate to reopen the issue if you feel this still applies.
