### ISSUE TITLE
Provisioning engine cannot remove permissions on Groups

### ISSUE THREAD

**Issue by LenCardinal** [OfficeDev/PnP-Sites-Core#375]
The provisioning engine cannot remove permissions assignments assigned on Groups. In one scenario, requirement was to change as site's Members group permissions from **Edit** to **Contribute**. This was done in a reference site. The provisioning template handled adding Contribute.  but there is no XML schema available for removing permissions, so **Edit** had to be removed with PowerShell script.

**Comment by PaoloPia** [comment]
Hi Len,
Thanks for your feedback. Usually we do not support removal of artifacts/information, to avoid unintentional loose of data/information. I will close this item.

**Comment by LenCardinal** [comment]
I agree with the spirit of not removing settings by default. And to force the developer to modify the XML to add any "remove" type of directives. But, regarding Permissions on a Group, the issue reported here seems like an oversight.

For Features, there is the ability for the developer to modify XML and add to <pnp:Features> a <pnp:Feature ID="XYZ" Deactivate="true" />. So there is an example of the library providing ability to "remove" something. Note that the library does NOT include Deactivate statements when generating XML. Which is in line with the philosophy of not removing settings by default.

But, here, there are good reasons to customize permission levels. Especially in dial-tone service scenarios where a company is building a provisioning system for thousands of sites, and wants to trim down "Member" permissions in general.  my customer is a retail chain building sites for store kiosk workers...who need to edit documents, but should not be allowed to change library columns, add Apps, etc.

I was able to remove the permissions using PnP cmdlets. I could have done the same with PnP C# libraries. But not sure why this particular detail is an issue and we have to force developers to reach for code here, especially when there is precedent with support for deactivating Features.
