### ISSUE TITLE
SetAvailablePageLayouts / GetPageLayoutListItemByName doesn't behave as expected

### ISSUE THREAD

**Issue by arangas** [OfficeDev/PnP-Sites-Core#383]
I'm writing a console app that calls `SetAvailablePageLayouts()`. This uses `GetPageLayoutListItemByName()` internally. I'm finding some unexpected behaviour in the latter:

1. Information about the page layout file is read from the file system
2. The page layout has to be located in a certain place on the file system, and this behaviour can't be overridden/changed with a different parameter

Unfortunately these restrictions mean I can't use this method. (Possibly it is designed to work with the provisioning template XML engine?)

Is it necessary to read from the file system or could the method be rewritten to remove this dependency?

**Comment by PaoloPia** [comment]
Hi Alex,
Thanks for your feedback. The SetAvailablePageLayouts() method creates an XML excerpt that is stored in a property bag item, accordingly to the out of the box behavior of SharePoint. Within the generated XML we store the site relative URL of the Page Layouts, with a URL like "_catalogs/masterpage/file.aspx", and we do not reference the file system but we simply play around the file name and path using the System.IO.Path type. I will close this item, but if you need any further help, please do not hesitate to ask a question on Yammer: aka.ms/OfficeDevPnPYammer. Thanks.
