### ISSUE TITLE
CLIENTSDKV15

### ISSUE THREAD

**Issue by braegelno5** [OfficeDev/PnP-Sites-Core#389]
CLIENTSDKV15 is defined also on DEBUG16/RELEASE16 *.csproj settings in core and test on master and dev

**Comment by jansenbe** [comment]
For now it indeed is...once we officially start supporting 2016 this might change depending on the CSOM differences we encounter between the 15 and 16 distributions

**Comment by braegelno5** [comment]
that means 15 stands for SP15 on prem; 16 for SP16 on prem and without a number is SPonline?

**Comment by jansenbe** [comment]
correct. SPO is the default...the compiler directives are used to alter the code for SP15 and SP16

**Comment by jansenbe** [comment]
Closing this issue..was more a question than an issue and the question has been answered
