### ISSUE TITLE
Fields and View with localized sites

### ISSUE THREAD

**Issue by wictorwilen** [OfficeDev/PnP-Sites-Core#39]
We have an issue where we export a Task list from a Project site, created in Swedish. When we try to apply the template to another Swedish site we get an error saying the column "Description" does not exist. If we rename the field link for the Calendar view of the Task list from Description to Beskrivning (Swedish) it all works as expected.

**Comment by PaoloPia** [comment]
Hi Wictor, is this issue still open on your side? Thanks.

**Comment by erwinvanhunen** [comment]
I will close this issue. We have made considerable changes to the provisioning engine allowing multilingual templates. Do not hesitate to reopen the issue if it is still applicable
