### ISSUE TITLE
extracting template from rootsite generates incorrect result

### ISSUE THREAD

**Issue by erwinvanhunen** [OfficeDev/PnP-Sites-Core#4]
Tokenizer incorrectly replaces document template url with {site} token when generating template from root site. 
ExtractObjects in list instance does not resolve list from base template due to incorrect url matching.

**Comment by braegelno5** [comment]
i have a PR for this, you will find it here:
https://github.com/OfficeDev/PnP-Sites-Core/commit/f5a4c964c768e9f9cd1ad9aaa5aa1822a688e40c

**Comment by PaoloPia** [comment]
This one should have been fixed by this: https://github.com/OfficeDev/PnP-Sites-Core/pull/326
