### ISSUE TITLE
TimeZone attribute marked as "optional" but not optional

### ISSUE THREAD

**Issue by LenCardinal** [OfficeDev/PnP-Sites-Core#407]
In the latest schema (Feb 2016 mid-month), the TimeZone attribute is decorated as "optional".  but the provisioning engine throws a "Value cannot be null" exception if it is omitted.

Also, the documentation should be enhanced to indicate TimeZone="0" should be used to avoid overriding a site's time zone.

```
<xsd:attribute name="TimeZone" type="pnp:ReplaceableInt" use="optional">
   <xsd:annotation>
        <xsd:documentation xml:lang="en">
         The Time Zone that is used on the server, optinal attribute.
       </xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>
```

Exception and stack trace when `"TimeZone="` is omitted:
```
Exception: Value cannot be null.
at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo 
 info, Boolean parseDecimal)
 at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
 at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLPnPSchemaV201512Formatter.ToProvisioningTemplate(Stream template, String identifier)
 at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLPnPSchemaFormatter.ToProvisioningTemplate(Stream template, String identifier)
 at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLTemplateProvider.GetTemplate(String uri, String identifier, ITemplateFormatter formatter)
 at OfficeDevPnP.PowerShell.Commands.Branding.ApplyProvisioningTemplate.ExecuteCmdlet()
 at OfficeDevPnP.PowerShell.Commands.SPOCmdlet.ProcessRecord()
 + CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException

```

**Comment by PaoloPia** [comment]
Thanks, I just fixed the issue in the DEV branch. https://github.com/OfficeDev/PnP-Sites-Core/pull/408
About the documentation update, it will come as soon as we will have time (we do that in our spare time). Thanks.

**Comment by LenCardinal** [comment]
This seems like more than a documentation update. It is a bug. The attribute is optional, but not truly optional…

Len Cardinal, Principal Consultant | Microsoft Services, New York / New Jersey | W: (646) 225-4314 | M: (917) 701-0121 | lenc@microsoft.com

**Comment by PaoloPia** [comment]
Hi Len,
You are right, and in fact - as I stated in my previous answer -  I already fixed the bug, and the fix has been merged in the DEV branch of this open source community project. The next monthly release will be available for everybody in the master branch in early March.

Later on, we will also try to enhance the documentation, as you suggested. However, because everybody in this community is contributing for free and in her/his own spare time, please do not always expect real-time responses like you had this time, because we cannot guarantee that.

Thanks again for your feedbacks.

**Comment by LenCardinal** [comment]
Yeah, apologies, read the email notifications out of order…saw you had reported a code fix after I sent the mail.

Let me know if there is anything I can do to help.
