### ISSUE TITLE
SharePoint 2013 - On-premises testing

### ISSUE THREAD

**Issue by VesaJuvonen** [OfficeDev/PnP-Sites-Core#418]
Help needed on the SharePoint 2013 on-premises testing around the PnP Core component and site provisioning engine.

**Comment by rgueldenpfennig** [comment]
I'm currently using the PnP Core Framework at a SharePoint on-premise project. Where are your priorities in testing the core components?

**Comment by VesaJuvonen** [comment]
Right now it's really the general testing around the on-premises with different setup... like lists, field types and other typical provisioning logic. In general the Core component capabilities should be pretty stable for on-premises, but getting random things tested, possible issues reported or even fixed with pull requests is the key. 

We are slightly struggling on the resourcing around testing on-premises in the Core team (also due our day jobs), so all help on this side is more than welcome.

**Comment by lanegoolsby** [comment]
I am using the PE heavily in a on-prem 2013 project right now (the template XML file is a little over 60k lines). In it we are creating lists, libraries, default data rows, groups, and wiki pages. I have noticed a couple minor things that I have opened issues for (and will issue PR's for once I get a minute to come up for air), but for the most part it works quite well. I would definitely qualify this project as 'typical provisioning logic'.

**Comment by rgueldenpfennig** [comment]
> but for the most part it works quite well
Same here. I'm currently working at a customer where we use the PnP Core Framework to create publishing pages, various lists and libraries, term set imports, display templates, web parts and most important migrating hundreds of thousands of items.
It works quite well but mostly it lacks of functionality regarding the handling of publishing pages. It's not possible to create pages with a specified content type or to create a page in a sub folder. So we developed that on our own.
We have also some hundred integration tests that work against the PnP library.

**Comment by Unkz** [comment]
So, how shoudl I deliver test results? Report bugs, fix bugs, etc. I have already made number of tests and made some corrections for instance in Security object handler (e.g. added possibility to use parameter in user name added to group).
So, what next? Report bugs, fix and create pull requests?

**Comment by VesaJuvonen** [comment]
Sorry for small delay on response and thanks everyone for providing input on this.. Please do report any bugs or issues as Issues in GitHub, so that we get them recorded. If you are already fixing things as you encounter them, pull requests are also more than welcome.

**Comment by VesaJuvonen** [comment]
Will close this one for now, since too generic to track. If there's any specific issues, please report them and we'll look for assistance on specific areas. thx.
