### ISSUE TITLE
Documentation assistance - Core component in general

### ISSUE THREAD

**Issue by VesaJuvonen** [OfficeDev/PnP-Sites-Core#420]
We would need assistance on the additional documentation around the Core component. This can be additional inlins documentation in the code or writing additional md files explaining specific usage scenarios, like following (one md per topic).

- Connect to SPO / On-premises
- Create site columns and content types 
- Create site collections and sub sites 
- Create lists and libraries
- Adjust site settings
- Apply branding elements
- Usage of custom actions with JS embedding
- ...

MD documentation for the Core component should be placed on the PnP-Guidance at the https://github.com/OfficeDev/PnP-guidance - if topic is specific for the Core component, please prefix the md file as PnPCore-.

You can also assist by updating existing linked MSDN documentation by providing updates on the existing md files. PnP MSDN documentation is at http://aka.ms/OfficeDevPnPMSDN.

**Comment by srirams007** [comment]
we have added the documentation for the list provided in the task. Please go through the documentation and let me know the feedback. Thanks.

**Comment by VesaJuvonen** [comment]
Will close up for now, since too generic and much more detailed guidance around the documentation guidelines would be needed.
