### ISSUE TITLE
Testing improvements - Core components

### ISSUE THREAD

**Issue by VesaJuvonen** [OfficeDev/PnP-Sites-Core#421]
Unit/integration testing improvements for Core component extension methods. We have already Core component test project with 300 tests, but would need assistance on increasing the coverage around the additional method to get included to tests.

All contributions on this side are highly welcome. 

Additional ideas and input around improved provisioning engine testing is also highly welcome.

**Comment by PieterVeenstra** [comment]
@VesaJuvonen, what is the current status of the existing tests. I had a look into the unit tests in the projects and I find that the PowerShell tests are failing. SI this something in my environment or are these tests not ready to run yet. The initial connects seem to be working.

**Comment by VesaJuvonen** [comment]
Since this is too generic issue, will close up for now.
