### ISSUE TITLE
Importing workflows creates multiple instances of the same workflow

### ISSUE THREAD

**Issue by PieterVeenstra** [OfficeDev/PnP-Sites-Core#429]
I've exported site with list workflow. Then I imported this workflow and I'm getting multiple instances of the exported workflow.

Every time I run the following command I get another instance of the same SPD workflow:

Apply-SPOProvisioningTemplate C:\TFS\Installer\Data\WebTemplates\Home\template.xml.updated -Handlers Workflows

**Comment by m-carter1** [comment]
This looks like the same issue here #323

We have a fix almost ready to submit

**Comment by PaoloPia** [comment]
This one has been closed by PR #436 .
