### ISSUE TITLE
File deployment to Theme Catalog fails on Subsites

### ISSUE THREAD

**Issue by lafe** [OfficeDev/PnP-Sites-Core#44]
I have encountered an issue on-premise while using the Site Provisioning Engine. When trying to deploy files to a subsite, the Engine deploys those files to the wrong folder (e.g. "/sites/TargetRoom/Subsite/sites/TargetRoom/_catalogs/theme/15") instead of the Site Collection Theme Catalog that is present in the Root Web.
The problem is that the "{themecatalog}" token is replaced correctly with the URL to the Theme Catalog in the Root Web, but the following steps assume that the folder is located in the Subsite the Engine is working on.

**Comment by PaoloPia** [comment]
Because the proposed solutions are closed, I will close this one as well. Thanks.
