### ISSUE TITLE
typeof(XMLPnPSchemaV201508Formatter) in XMLPnPSchemaV201512Formatter

### ISSUE THREAD

**Issue by luismanez** [OfficeDev/PnP-Sites-Core#446]
It's not causing any issue, but it's more coherent if we use the typeof(XMLPnPSchemaV201512Formatter) in the XMLPnPSchemaV201512Formatter class (following what it's done with the other formatters. Not it is:

Stream stream = typeof(XMLPnPSchemaV201508Formatter)
.Assembly                .GetManifestResourceStream("OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.ProvisioningSchema-2015-12.xsd");

I'm gonna send a new Pull request to change that.

Thanks!

**Comment by luismanez** [comment]
added Pull request to change this:
https://github.com/OfficeDev/PnP-Sites-Core/pull/447

**Comment by VesaJuvonen** [comment]
Fixed with the merged pull request.
