### ISSUE TITLE
Provisioning List based lookups works by luck (Apha order based)

### ISSUE THREAD

**Issue by gavinbarron** [OfficeDev/PnP-Sites-Core#475]
If it works.

Currently when lists are provisioned they are created in the order that they exist in the provisioning template.

If I have two lists, AList and BList where AList contains a list based lookup to BList provisioning fails when attempting to create the lookup column to a list that does not yet exist.

Provisioning succeeds when the lookup is in BList pointed to AList.

**Comment by lanegoolsby** [comment]
If you have the ID for the list in the field XML as List="Lists/MyList" this will happen. Instead use the token for the list (e.g. List="{listid:MyList}". This will prompt the engine to come back later and fix the linkage for the lookup field once all the lists have been created.

**Comment by gavinbarron** [comment]
Awesome! looks like I'd compiled my Partner Pack against an old version of the PnP Core.
