### ISSUE TITLE
Provisioning Engine - Publish file as major version

### ISSUE THREAD

**Issue by luismanez** [OfficeDev/PnP-Sites-Core#484]
As far as I've experienced, there's no way to publish a File in Major version from the Provisioning engine. Perhaps depends on how the Lib is configured, but for instance, with the OOB Master page gallery, the files (Layouts, Master pages, Display templates) are provisioned but not published as major versions. This is the pnp:File node I'm using:

```xml
<pnp:File Src="..\Assets\DisplayTemplates\Content Web Parts\Custom_Item_News.html" Folder="~masterpagecatalog/Display Templates/Content Web Parts" Overwrite="true">
          <pnp:Properties>
            <pnp:Property Key="Title"  Value="Custom Default Item" />
            <pnp:Property Key="ContentTypeId" Value="{contenttypeid:Item Display Template}" />
            <pnp:Property Key="MasterPageDescription"  Value="Displays the Search Results default item in a custom way." />
            <pnp:Property Key="UIVersion"  Value="15" />
            <pnp:Property Key="TemplateHidden"  Value="0" />
            <pnp:Property Key="TargetControlType"  Value=";#Content Web Parts;#" />
            <pnp:Property Key="DisplayTemplateLevel"  Value="Item" />
            <pnp:Property Key="ManagedPropertyMapping"  Value="'Link URL'{Link URL}:'Path','Line 1'{Line 1}:'Title','Line 2'{Line 2}:'','FileExtension','SecondaryFileExtension'" />
          </pnp:Properties>
        </pnp:File>
```

I'm gonna do a Pull Request with a possible temporary solution to this, but IMHO the right way to fix it should be to allow a **Level** attribute in the pnp:File xml node.

**Comment by MarkStokes-outlook** [comment]
I would also like the ability to provision my master laws and page layouts as Published and Approved.

**Comment by MarkStokes-outlook** [comment]
*master pages

**Comment by luismanez** [comment]
with latest PnP Schema, now is possible to set the Level of the File:
https://github.com/OfficeDev/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2016-05.md

so we can close this issue.
/cc @VesaJuvonen @PaoloPia

**Comment by bartdonninger** [comment]
Hello,

The latest schema does indeed offer the attribute Level on File and Directory elements. But when i want to provision my masterpages to the MasterPage Gallery they do not get published to a 1.0 version.

Can anyone confirm if this is still an issue for them as well?

**Comment by sandermoes** [comment]
Same issue for me on SP 2013. Masterpages en page layouts remain un-published.

**Comment by bengtmoss** [comment]
@bartdonninger , same here: a page layout with Level="Published" is still not published.
