### ISSUE TITLE
Missing token for group-id - needed for user-field deployment

### ISSUE THREAD

**Issue by jakobnotseth** [OfficeDev/PnP-Sites-Core#503]
When deploying user-fields, you sometimes want to fill in a specific group-id in UserSelectionScope.
I suggest creating a token `{groupid:<x>}`, where `<X>` is either sitegroup-title, or associatedmembersgroup, associatedownersgroup, associatedvisitorsgroup.
This needs to be checked during Field-provisioning.

**Comment by erwinvanhunen** [comment]
Thanks for reporting this one. The groupid token has been added. See PR #724 for details. I will close this issue.
