### ISSUE TITLE
Files into the masterpage gallery fail to honour the CT setting in latest PnP Nuget version beyond 2.2.1603.0

### ISSUE THREAD

**Issue by weshackett** [OfficeDev/PnP-Sites-Core#529]
When using the apply template from the PnP provisioning it now no longer correctly sets the content type for a page layout in the master page gallery.

I've just updated both CSOM and PnP Core 16 Nuget 

When using:
OfficePnpCore16 v2.2.1603

This xml works and correctly sets the CT to Page Layout in the master page item

`<pnp:File Src=".\Assets\BlankWebPartPageCopy.aspx" Folder="{masterpagecatalog}/" Overwrite="true">
					<pnp:Properties>
						<pnp:Property Key="Title" Value="My Custom Page Layout" />
						<pnp:Property Key="MasterPageDescription" Value="Just a custom page layout. Copied from Default Blank Webpart page layout" />
						<pnp:Property Key="ContentTypeId" Value="0x01010007FF3E057FA8AB4AA42FCB67B453FFC100E214EEE741181F4E9F7ACC43278EE811" />
						<pnp:Property Key="PublishingAssociatedContentType" Value=";#Welcome Page;#0x010100C568DB52D9D0A14D9B2FDCC96666E9F2007948130EC3DB064584E219954237AF390064DEA0F50FC8C147B0B6EA0636C4A7D4;#"/>
						<pnp:Property Key="UIVersion" Value="15" />
					</pnp:Properties>
				</pnp:File>`

When you update the above to newer versions the same XML will not set the Content Type to be Page Layout but instead it remains as Display Template (the mp gallery default)
Removing the latest PnP version back to OfficePnpCore16 v2.2.1603 resolves the issue with no other changes needed to the code or templates.``

**Comment by PaoloPia** [comment]
As shared on Yammer, this is a known bug that has already been fixed. I will close it. Thanks for your support.
