### ISSUE TITLE
Infopath forms not working 

### ISSUE THREAD

**Issue by BigBrahma** [OfficeDev/PnP-Sites-Core#530]
- I have list which is customized using InfoPath. 
- I am using the below code for site provisioning.  List is created but InfoPath form is not loading. it is just displaying as default SharePoint list forms.
- Can you please let me know is there is any other way to get InfoPath form?

 

```
_ProvisioningTemplate template = GetProvisioningTemplate(defaultForeground, templateWebUrl);

            // APPLY the template to new site from 
            if (targetWebUrl != "")
            {
                ApplyProvisioningTemplate(targetWebUrl, template, defaultForeground);
            }
_```

**Comment by VesaJuvonen** [comment]
Hi BigBrahma,
we do not unfortunately have plans for supporting InfoPath in the PnP export / import process. This means that if you'd like use InfoPath with the engine, you should be looking into implementing this as extensibility provider or alternatively create a pull request to PnP Core, which would support this.

Thx for your input.

**Comment by StefanLankester** [comment]
BigBrahma provisioning InfoPath forms for customization of SharePoint isn't easily possible.
After you customized the SharePoint list form there is a direct relationship between the SharePoint list and the InfoPath form based on the List Guid. The same is true for all your data connections with SharePoint lists.

My advice if you still like to use InfoPath form is that you follow a different approach by using the SharePoint Forms Library.

Provision you InfoPath xsn template file into the "FormServerTemplates" (Form Templates) library

Create/Provision Content Types 0x010101 XmlDocument
<ContenType
    ID="0x01010100..Your CT ID"
    Name=".."
    Description=".."
    Group=".."
    Inherits="TRUE"
    RequireClientRenderingOnNew="FALSE"
    Version=".."
    <FieldRefs>
      <FieldRef Name="IPFormEdit" ID="{3AE63AF5-C142-4D51-9231-50540891FD3D}" />
      <RemoveFieldRef ID="{fa564e0f-0c70-4ab9-b863-0177e6ddd247}" Name="Title" />
      .....
       Your other field definitions
      ......
    </FieldRefs>
    <DocumentTemplate TargetName="~site/FormServerTemplates/YourInfoPathTemplate.xsn" />
  </ContentType>

Create/Provision  custom Form Library list(s) (list template 115) and bind your Content Types

During creation of the InfoPath list form you can use the SharePoint list template but alway publish the form to a local file folder (not to SharePoint!!!).

**Comment by StefanLankester** [comment]
The following trick helps you easily converting your InfoPath Views into HTML and CSS:

- Rename the "xsn" extension of your InfoPath template file into "cab". 
- Extract the cab file with the result you now will have all seperate xml, xsd and xsl source file from the InfoPath xsn file. 
- The files you need for converting your InfoPath views into HTML and CSS are > Template.xml and the .xsl files of your views. 
- In your web browser open the page "Free Online XSL Transformer (XSLT) - FreeFormatter.com" : http://www.freeformatter.com/xsl-transformer.html. 
- Paste your template.xml file into "XML Input" field and your .xsl view file into the "XSL Input" field. 
- Optional when you like change the "Indentation Level" dropdown selection into "Tab Delimeted". 
Press the "Transform XML" button. 
- The HTML result of the transformed xml can be pasted into your own html file.

Todo for using this initial HTML with the CSS for SharePoint List forms:
- If you like create seperate CSS files by removing the CSS from the style elemen in the header of your into html converted InfoPath views
- Edit your DispForm.aspx, EditForm.aspx and NewForm.aspx add (3) Content Editor Web Parts with contentlinks to CSS, HTML and Java Script.
- With CSS hide exit list Web Part on the list form aspx pages.
- Develop Java Script for your form functionality and moving the standard list field controls into your HTML form.
