### ISSUE TITLE
Add DeleteAllGlobalNavigationNodes method to Core component as web extension

### ISSUE THREAD

**Issue by VesaJuvonen** [OfficeDev/PnP-Sites-Core#54]
Good suggestion from Yammer group to make things slightly simpler: https://www.yammer.com/itpronetwork/#/Threads/show?threadId=567671742

"Using the Office Dev PnP we provision Team sites. We want to build up navigation from scratch, both the Global Navigation and Current Navigation. I'm using the Web.DeleteAllQuickLaunchNodes, to delete all Current Navigation nodes. To delete the Global Navigation nodes, I'm calling the web.DeleteNavigationNode method for each navigation node. 
 Is there a method, or can this be added, to delete all Global Navigation Nodes in a single call, something like Web.DeleteAllGlobalNavigationNodes?"

**Comment by erwinvanhunen** [comment]
Implemented web.DeleteAllNavigationNodes(NavigationType) method with PR #56 . Closing this issue.
