### ISSUE TITLE
Multilanguage not supported

### ISSUE THREAD

**Issue by TVDKoni** [OfficeDev/PnP-Sites-Core#547]
Provisioning does not support multi language. Resources are not exported and export is not running in the language the site is installed. The export is running in the language the user has configured in his profile. May only partially. Some stuff is exported in the site installed language and some stuff is exported in the user language. An example of such an export can be found here:
[http://pastebin.com/LtkweW9f](http://pastebin.com/LtkweW9f)
There you can see exported roles who are in german. If the user language on the target site is not german, the import will fail. In addition the site field TrivadisTileSizeX is exported in englisch. And not in german as the roles. Export and import should be related to the language a SharePoint site is installed.

Is this problem already well known? Is there a fork already working on this issue? Already any plans to make provisioning multi lingual?

**Comment by erwinvanhunen** [comment]
Hi,

We have not much control over the language we retrieve artifacts in a site unfortunately. We request the artifact from the server and will add to the template what the server provides us with. Indeed we do not extract culture specific resources from those artifacts that support it (lists title, field title, web title and custom action title).

So while we do not provide you with the info during extraction, we do support multilanguage functionality during provisioning. 

See http://www.erwinmcm.com/multilingual-provisioning-templates-with-the-office-365-developer-patterns-and-practices-provisioning-engine/ an explanation how to create a multi-language enabled template.

Having said that, I think it's a valid request and I will put on the todo list to allow for exporting resource values. We will most likely end up generating a resource file on the fly that we reference to in the generated template and replace the found values with appropriate keys. This will most likely mean that the keys will not be that readable (as they will have to be generated).

**Comment by TVDKoni** [comment]
Hi Erwin

Many thanks for the commit. Exporting resources works like a charm. Also found the reason why a lot of German stuff got exported. I had to set the locale and MUI language from the current exporting user to the same value the web is using:

                        Microsoft.SharePoint.Client.User user = context.Web.CurrentUser;
                        context.Load(user);
                        context.Web.Context.Load(context.Web.RegionalSettings);
                        context.Web.Context.Load(context.Web.RegionalSettings.TimeZone, tz => tz.Id);
                        context.ExecuteQuery();
                        PeopleManager peopleManager = new PeopleManager(context);
                        int lcid = (int)context.Web.RegionalSettings.LocaleId;
                        CultureInfo siteCulture = CultureInfo.GetCultureInfo(lcid);
                        var muiLanguages = siteCulture.Name;
                        var customRegionalSettings = "False";
                        var locale = "" + lcid;
                        var timeZoneID = "" + context.Web.RegionalSettings.TimeZone.Id;
                        peopleManager.SetSingleValueProfileProperty(user.LoginName, "SPS-MUILanguages", muiLanguages);
                        peopleManager.SetSingleValueProfileProperty(user.LoginName, "SPS-RegionalSettings-FollowWeb", customRegionalSettings);
                        peopleManager.SetSingleValueProfileProperty(user.LoginName, "SPS-Locale", locale);
                        peopleManager.SetSingleValueProfileProperty(user.LoginName, "SPS-TimeZone", timeZoneID);
                        context.ExecuteQuery();

Now the export looks perfect.

**Comment by erwinvanhunen** [comment]
Great to here! I will close this issue then.
