### ISSUE TITLE
 ContentTypeExistsById method with child content types

### ISSUE THREAD

**Issue by VesaJuvonen** [OfficeDev/PnP-Sites-Core#555]
#### Category
[x] Bug
[ ] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[x] SharePoint 2016
[x] SharePoint 2013

If SharePoint on-premises, what's exact CU version: all.

#### Expected or Desired Behavior
When you have 2 content types where one is inherited from other associated to a list. 

#### Observed Behavior
ContentTypeExistsById does use starts with on solving the ID, so matching is not accurate.

#### Steps to Reproduce
Create two content types one inherited from the other. Associate to list or library with an order of child first. Run method call for the parent CT -> you will get a wrong CT as result. 

Original fix suggestion from Lars at #153 is not reliable enough, but has the right idea. Suggestion from @okms seems correct. We'll take this as Core team task to fix, but absolutely will credit you guys on finding it.

**Comment by PaoloPia** [comment]
Fixed here #570.
