### ISSUE TITLE
Sign the assembly

### ISSUE THREAD

**Issue by matthemsteger** [OfficeDev/PnP-Sites-Core#59]
While it is entirely possible to get the source and sign the assembly locally, it would make it a lot easier (especially for just getting it via nuget) to have the assembly signed by default.

In the enterprise it is very common to require signed assemblies, and if you are using this in any kind of assembly that is required in on-prem inter-op with farm solutions, etc .. then there is a high likelihood that signed assemblies are needed.

**Comment by VesaJuvonen** [comment]
We are looking into this one and should have signed assemblies available starting from December master merge. Will keep this one open until then.

**Comment by PaoloPia** [comment]
In January 2016 we released signed assemblies. Thus, I will close this one.
