### ISSUE TITLE
Allowed Content Types of Document Set Content Type not setup correctly when Apply-SPOProvisioningTemplate applied to site

### ISSUE THREAD

**Issue by NPrice99** [OfficeDev/PnP-Sites-Core#599]
Document Set Settings :-

 Available Content Types not setup correctly - leaves 'Document' content type in - in site cloned from it has been removed from Allowed Content Types.

 

#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[ X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
in cloned from site 'Document' Content Type has been removed from Allowed Content Types.

#### Observed Behavior
Default set - 'Document' Content TYpe is in Allowed Content Types not the Content Type which was set up in the original site

#### Steps to Reproduce
Create document set with allowed Content Types set to another Content Type Get-SPOProvisioingTemplate  then Apply-SPOProvisioningTemplate.

Observe result in new site.

#### Submission Guidelines
_Delete this section after reading_
- All suggestions or bugs are welcome, please let us know what's on your mind.
- If you are reporting any issues around PnP Core Component, please reproduce the issue with latest release.
- If you are reporting issue around PnP Provisioning Engine, please share the xml template, if possible.
- If you are reporting an issue around any of the samples, please ensure that you have clear reference on the sample and possibly code file, which should be fixed.
- If you have a general question, please use the [PnP Yammer Group](http://aka.ms/OfficeDevPnPYammer).
- Remember to include sufficient details and context.
- If you have multiple suggestions or bugs please submit them in seperate bugs so we can track resolution.

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
Nice catch. We've fixed this as part of the upcoming provisioning engine test cases...within a few days this fix will end up in the dev branch. Production release will be for the August update. I'm already closing this issue but feel free to re-open when it still is not working for you. I've pasted a sample definition I used in the test case

```XML
    <pnp:ContentType ID="0x0120D52000E5DBFFDBB86B454096672F072D473FC8" Name="CT_21" Description="CT 21" Group="PnP Demo">
      <pnp:FieldRefs>
        <pnp:FieldRef ID="{92BC6A41-D501-4FE2-938E-17FBF574A7CB}" />
        <pnp:FieldRef ID="{56407FDD-C7FA-4321-8FA5-06B7AF970519}" />
      </pnp:FieldRefs>
      <pnp:DocumentSetTemplate>
        <pnp:AllowedContentTypes>
          <pnp:AllowedContentType ContentTypeID="0x0101005D4F34E4BE7F4B6892AEBE088EDD215E"/>
        </pnp:AllowedContentTypes>
        <pnp:DefaultDocuments>
          <!-- Note that the FileSourcePath points to location on the FileProvider (filesystem/Azure/SP) relative to the path of this XML file. Files will
               be added without them being referenced in the Files section of the template -->
          <pnp:DefaultDocument Name="CT21Document.docx" ContentTypeID="0x0101005D4F34E4BE7F4B6892AEBE088EDD215E" FileSourcePath="./CT21Document.docx"/>
        </pnp:DefaultDocuments>
        <pnp:SharedFields>
          <pnp:SharedField ID="{92BC6A41-D501-4FE2-938E-17FBF574A7CB}"/>
        </pnp:SharedFields>
        <pnp:WelcomePageFields>
          <pnp:WelcomePageField ID="{92BC6A41-D501-4FE2-938E-17FBF574A7CB}"/>
        </pnp:WelcomePageFields>
      </pnp:DocumentSetTemplate>
    </pnp:ContentType>
```

**Comment by abhitalks** [comment]
Using the Provisioning Schema 2016/05.

The source site has the lists and/or libraries which have the default content type removed and a custom content type from a content type publishing hub is applied.

When the provisioning engine does the `GetProvisioningTemplate` to generate a template, then those lists and/or libraries have two content types associated. One, the custom content type and the second one is the default content type for that list/library.

Typically, the template element inside `<pnp:ContentTypeBindings>` of the `<pnp:ListInstance` contains an extra binding as:

`<pnp:ContentTypeBinding ContentTypeID="0x0120" />`

Ideally it should have only one binding like

`<pnp:ContentTypeBinding ContentTypeID="0x0101009148F5A04D......" />`

This causes the lists/libraries to have two content types associate (_one being the default_) on the new (_target_) site.

**Comment by prawnz** [comment]
I just encountered this with the latest schema, The AllowedContentType is not setting
