### ISSUE TITLE
V201605 schema formatter not in may release of pnp core and pnp PowerShell (2.4.1605)

### ISSUE THREAD

**Issue by baywet** [OfficeDev/PnP-Sites-Core#613]
#### Category
[ x] Bug
[ ] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
V201605 schema formatter not in may release of pnp core and pnp PowerShell (2.4.1605)

#### Observed Behavior
Hi,
It's more of a question than a real issue.
One would expect the 201605 version of provisioning schema documented here https://github.com/OfficeDev/PnP-Provisioning-Schema would be available with may release of office pnp PowerShell (online) 2.4.1605

But when we try to use it we get a null reference exception and decompiling the dll explains why, the formatter is just not here.
![pnp201605schemaformatter](https://cloud.githubusercontent.com/assets/7905502/15900548/e00d702e-2d6d-11e6-9850-58ba38957c11.png)

Is is just me misinterpreting or does it make sense to expect the formatter to be here?
Regards

**Comment by SuleymanA** [comment]
After some trial and error, costing me a lot of time (first reaction was to think that my template had errors.........). I came to the same conclusion. If a template file is used with 201605 schema the xmlformatter throws a null reference error. Just changing the schema to 201512 solves the issues...

**Comment by PaoloPia** [comment]
Hi,
The schema definition process happens before the real implementation in the engine. In fact, in the schema home page (https://github.com/OfficeDev/PnP-Provisioning-Schema#current-implemented-version-in-the-pnp-provisioning-engine) we declare what is the latest schema version implemented in the engine. The new schema 201605 is still under development from an engine perspective. I will close this issue. Thanks.

**Comment by baywet** [comment]
Hi @PaoloPia , thanks for the clarification.
Then I think the 201605 should not be under the current implemented version section (the fact that it's bigger can make people think all these versions are currently implemented).
There's also a C/P error for the version 201605, the "in order to reference" has 201512 instead of 201605. Should I open an issue other there? or even better, a PR?

**Comment by PaoloPia** [comment]
I can fix it. Thanks.
