### ISSUE TITLE
Apply-SPOProvisioningTemplate fails for on-premises environment

### ISSUE THREAD

**Issue by estruyf** [OfficeDev/PnP-Sites-Core#631]
Hi,

I'm currently trying to apply an exported template to a new site via the Apply-SPOProvisioningTemplate cmdlet on a on-premises environment (sp2013Feb2016CU - 15.0.4797.1000). The template got exported without any errors, but when I try to apply it, I get the following error message:

```
Apply-SPOProvisioningTemplate : startIndex cannot be larger than length of string.
Parameter name: startIndex
At line:1 char:1
+ Apply-SPOProvisioningTemplate -Path meeting-template.xml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-SPOProvisioningTemplate], ArgumentOutOfRangeExcepti 
   on
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Branding.ApplyProvisioningTemp 
   late
```

Already installed the latest binaries for SharePoint 2013 (SharePointPnPPowerShell2013.msi). 

Any idea what's causing this?

Thanks,
Elio

**Comment by VesaJuvonen** [comment]
thx Elio, any change you could share the template and asset files with some of the core team members, so that we can do easy repro. We can't seem to find the combination to get this reproduced, so having material to do that would be great.

**Comment by estruyf** [comment]
@VesaJuvonen as uploading an XML and ZIP did not work, I uploaded it as a TXT file. So just rename it to XML. This is just an export of a default team site on my client's environment. Even this gives the same error.

Site template: [meeting-template.txt](https://github.com/OfficeDev/PnP-Sites-Core/files/318912/meeting-template.txt)

**Comment by juasmith** [comment]
I am seeing the exact same error when trying to apply in an on premises environment.  I'm running directly on server.

**Comment by estruyf** [comment]
@VesaJuvonen @erwinvanhunen the :bug: can be found on line 74 of the TokenParser file: [TokenParser.cs](https://github.com/OfficeDev/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/TokenParser.cs). The **web** object is used, I think this should be **rootWeb** instead.

**Comment by erwinvanhunen** [comment]
We made that change already to the dev branch yesterday evening. Could you use that one to test? (it's also in the version I mailed to you last night)

**Comment by estruyf** [comment]
@erwinvanhunen this problem got fixed by using the dev branch code.

**Comment by juasmith** [comment]
@erwinvanhunen how do I get access to the fix?

**Comment by mrpullen** [comment]
@juasmith my guess is you would pull the latest from the dev branch, compile it for SharePoint online, and copy the OfficeDevPnP.Core file from that build into your modules directory (C:\Program Files\WindowsPowerShell\Modules\SharePointPnPPowerShellOnline\2.5.1606.1)
