### ISSUE TITLE
Enabled attribute on custom action is not used

### ISSUE THREAD

**Issue by jansenbe** [OfficeDev/PnP-Sites-Core#653]
#### Category
[ ] Bug
[x] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[x] SharePoint 2016
[x] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Setting the Enabled property on a custom action implements this behavior:
-New action: adds when enabled = true, skip if enabled = false
-Existing action: drop if enabled is false

#### Observed Behavior
Attribute is not used at all

**Comment by PaoloPia** [comment]
Bert,
I've added support for the Enabled attribute during creation. However, for removal there is already the Remove attribute.
