### ISSUE TITLE
Can't compile the Dev Branch against the Debug 15

### ISSUE THREAD

**Issue by konraplo** [OfficeDev/PnP-Sites-Core#669]
Hi

I have just get the newst dev branch sources and I try to compile using Debug 15 (I'm working with SP 2013 on premisse). The problem is ObjectTermGroups class is using CSOM 16 api and cant be compiled using Debug 15

#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
The code could be compiled using Debug 15 (SP 2013 on premise)

#### Observed Behavior
The problem is ObjectTermGroups  clas is using CSOM 16 api and cant be compiled using Debug 15.

**Comment by PaoloPia** [comment]
Fixed. Thanks.
