### ISSUE TITLE
List versioning settings not downloaded into template

### ISSUE THREAD

**Issue by konraplo** [OfficeDev/PnP-Sites-Core#673]
Hi

If activate versioning in my List/DocLibrary, after downloading a template, settings like number of versions/drafts are not being download into template.

- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ x] SharePoint 2013

#### Expected or Desired Behavior
After downloading a template number of versions/drafts should be exported for corresponding List.

#### Observed Behavior
If activate versioning in my List/DocLibrary, after downloading a template, settings like number of versions/drafts are not being download into template.

#### Steps to Reproduce
Activate versioning in List/DocLibrary, set limit number of versions/drafts. Get provisioning template for this site.

KR
Konrad

**Comment by PaoloPia** [comment]
Hi,
Thanks for your contribution. The issue has been fixed and the fix is available in the DEV branch.

**Comment by konraplo** [comment]
Thx Paolo!:) It works fine but Minor/MaxVersionLimit are not privisoned. But I create extra Issue for this:)
