### ISSUE TITLE
Get-SPOProvisioningTemplate on SP 2013

### ISSUE THREAD

**Issue by ssandu** [OfficeDev/PnP-Sites-Core#691]
#### Category
[ x] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 15.0.4797.1000

Get-SPOProvisioningTemplate -Out "c:\temp\pnpdemo.pnp" -PersistBrandingFiles -Handlers All
gives the following  error
Get-SPOProvisioningTemplate : No connection, please connect first with Connect-SPOnline
At line:1 char:1
+ Get-SPOProvisioningTemplate -Out "c:\temp\pnpdemo.pnp" -PersistBrandingFiles -Ha ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-SPOProvisioningTemplate], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,SharePointPnP.PowerShell.Commands.Branding.GetProvis 
   ioningTemplate
with this TraceLog
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:25.2082	[OfficeDevPnP.Core]	[0]	[Information]	File pnpdemo.pnp retrieved from folder 	0ms	
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:25.2863	[Extraction]	[11]	[Debug]	Code execution scope started	0ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:25.2863	[Extraction]	[11]	[Debug]	Base template available: STS0template	0ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:25.2863	[Extraction]	[11]	[Debug]	ProgressDelegate registered	0ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:25.2863	[Extraction]	[11]	[Debug]	MessagesDelegate registered	0ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:25.2863	[Extraction]	[11]	[Debug]	PersistBrandingFiles is set to true	0ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:25.5363	[Regional Settings]	[11]	[Debug]	Code execution scope started	0ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:25.5832	[Regional Settings]	[11]	[Debug]	Code execution scope ended	54ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:25.5832	[Supported UI Languages]	[11]	[Debug]	Code execution scope started	0ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:25.6301	[Supported UI Languages]	[11]	[Debug]	Code execution scope ended	54ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:25.6457	[Fields]	[11]	[Debug]	Code execution scope started	0ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:25.7395	[Fields]	[11]	[Debug]	Context web is subweb, skipping site columns	102ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:25.7395	[Fields]	[11]	[Debug]	Code execution scope ended	102ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:25.7395	[Content Types]	[11]	[Debug]	Code execution scope started	0ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:25.8488	[Content Types]	[11]	[Debug]	Context web is subweb. Skipping content types.	95ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:25.8488	[Content Types]	[11]	[Debug]	Code execution scope ended	96ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:25.8488	[List instances]	[11]	[Debug]	Code execution scope started	0ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:26.8379	[Get Security]	[11]	[Debug]	Code execution scope started	0ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:26.9316	[Get Security]	[11]	[Debug]	Code execution scope ended	100ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:26.9316	[List instances]	[11]	[Debug]	Adding list: Documents - Shared Documents	1090ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:27.7910	[Get Security]	[11]	[Debug]	Code execution scope started	0ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:27.9004	[Get Security]	[11]	[Debug]	Code execution scope ended	95ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:27.9004	[List instances]	[11]	[Debug]	Adding list: MicroFeed - Lists/PublishedFeed	2052ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Warning: 0 : 2016-08-01 06:53:27.9004	[List instances]	[11]	[Information]	You are extracting a template from a subweb. List 'MicroFeed' refers to content types. Content types are not exported when extracting a template from a subweb	2053ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:28.3691	[Get Security]	[11]	[Debug]	Code execution scope started	0ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:28.4473	[Get Security]	[11]	[Debug]	Code execution scope ended	90ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:28.4473	[List instances]	[11]	[Debug]	Adding list: Site Assets - SiteAssets	2611ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:29.0254	[Get Security]	[11]	[Debug]	Code execution scope started	0ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:29.1191	[Get Security]	[11]	[Debug]	Code execution scope ended	95ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:29.1191	[List instances]	[11]	[Debug]	Code execution scope ended	3277ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:29.1191	[Features]	[11]	[Debug]	Code execution scope started	0ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:29.2441	[Features]	[11]	[Debug]	Code execution scope ended	127ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:29.2441	[Composed Looks]	[11]	[Debug]	Code execution scope started	0ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:29.2441	[Composed Looks]	[11]	[Information]	Retrieving current composed look	0ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:29.5879	[Composed Looks]	[11]	[Debug]	Code execution scope ended	338ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:29.5879	[Page Contents]	[11]	[Debug]	Code execution scope started	0ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:29.8691	[Page Contents]	[11]	[Debug]	Code execution scope ended	286ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776
PowerShell_ISE.exe Information: 0 : 2016-08-01 06:53:29.8691	[Extraction]	[11]	[Debug]	Code execution scope ended	4583ms	a4bd001f-6daa-4d1c-8e67-cb163b48b776

**Comment by erwinvanhunen** [comment]
The error message actually state the issue: Get-SPOProvisioningTemplate : No connection, please connect first with Connect-SPOnline

You will first have to issue the Connect-SPOnline cmdlet in order to create a session towards your server.

```powershell
Connect-SPOnline -Url http://yoursite -CurrentCredentials
Get-SPOProvisioningTemplate
```

I will close this issue, but if you still think the issue stands, do not hesitate to reopen it.

**Comment by ntinykumar** [comment]
I am getting the 403 error . Please let me know how to resolve this , See below error text 

PowerShell_ISE.exe Information: 0 : 2016-10-05 16:55:46.4911	[Extraction]	[9]	[Debug]	Code execution scope ended	110150ms	e7de50f3-15be-4b6a-8544-9447503e9d21
Get-SPOProvisioningTemplate : The remote server returned an error: (403) Forbidden.
At line:1 char:1
+ Get-SPOProvisioningTemplate -Out  .\DeploymentFreshpackage.xml
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-SPOProvisioningTemplate], WebException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Branding.GetProvisioningTemplate

**Comment by ntinykumar** [comment]
Hi Team, 
We have subsite within the site collection, Get and apply provision templates working for site collection but when same I use for sub site it shows the bellow warning and xml package does not included any content type list and fields associated to each other. 

Below is the warning I received while get-SPOpovisionTemplate by using below command 
Connect-SPOnline –Url https://DomainName.sharepoint.com/Sites/SC/Updates –Credentials QA
Get-SPOProvisioningTemplate -Out .\SubSiteStructureToTSW_UsingUpdates2.xml 

Warning: WARNING: You are extracting a template from a subweb. List 'xyz' refers to content types. Content types are not exported when extracting a template from a subweb

What could be the issue. Does content type which are created at subsite level does not import export by using PnP template provision solution ?

**Comment by cheindel** [comment]
Hello @ntinykumar, I cannot see how your comment is related to the original issue. If so, could you please explain in more detail?

Regarding your question about content types: This is by design.
Content types are always stored on site collection level. If you extract a subsite that is using such content types, you can still apply the template as a subsite within the same site collection.

Maybe this documents can help for better understanding about content types: https://msdn.microsoft.com/en-us/library/ms463016 / https://technet.microsoft.com/en-us/library/cc262735.aspx

If you want to re-use your content types in other site collections, the content type hub might be a solution for you: https://blogs.msdn.microsoft.com/chaks/2011/02/08/content-type-hub-faq-and-limitations/ / https://technet.microsoft.com/en-us/library/ee519603.aspx /

**Comment by ntinykumar** [comment]
Dear @cheindel , 

I am elaborating the question deeply below. 
We have two different Office 365 tenant, where one is QA and other is production having same plan from the Microsoft. 

We have site structure created in QA like Taxonomy/Site Columns/ Lists/ CT etc. that we need to move from QA to Production tenant. We have same site collection created as Publishing portal on both tenant. 

Now scenario is by using PnP provision (Get/Apply ProvisionTemplate commands from PowerShell online management) we are able to migrate the Site Collection level structure (Taxonomy/Site Columns/ Lists/ CT) from QA to Production tenant successfully and all is working. Now we have more subsites in QA with site structure like Taxonomy/Site Columns/ Lists/ CT  which we have to migrate on the production tenant using Get/Apply ProvisionTemplate commands , We are not able to migrate the site structure. Commands got successfully executed or sometime its shows error like which I sent in previous post. But no site structure have been created in production subsite however exported .xml file does have all things. 

Please let me know if you need more information about my problem 

Thanks, 
Nitinkumar Kakulde 
+91-9890336633
