### ISSUE TITLE
AddNavigationNode

### ISSUE THREAD

**Issue by gabbsmo** [OfficeDev/PnP-Sites-Core#693]
#### Category
[ ] Bug
[x] Enhancement

#### Environment
[x] Office 365 / SharePoint Online
[x] SharePoint 2016
[x] SharePoint 2013

#### Expected or Desired Behavior
AddNavigationNode should accept a string in addition to a Uri. This would allow adding relative urls to navigation.

#### Observed Behavior
Only absolute urls can be added to navigation. This is inconvenient when using save as template since the links wont work on new sites.

**Comment by erwinvanhunen** [comment]
You can actually send in a relative url. Just define your Uri object as follows:

var uri = new Uri(urlString, UriKind.RelativeOrAbsolute);

I will close this issue, but if you feel the issue still stands, do not hesitate to reopen it.

**Comment by gabbsmo** [comment]
Created this issue in together with this issue in PnP-PowerShell https://github.com/OfficeDev/PnP-PowerShell/issues/396
