### ISSUE TITLE
Custom ProvisiningExtensibilityHandler GetTokens method is never invoked.

### ISSUE THREAD

**Issue by luismanez** [OfficeDev/PnP-Sites-Core#698]
I've created a custom ProvisiningExtensibilityHandler implementing the IProvisioningExtensibilityHandler interface. The provider is registered OK, and the Extract and Provision methods are invoked as expected, however, the GetTokens method is never invoked. I think this is because some code in the ExtensibilityManager is still expecting the old interface "IProvisioningExtensibilityProvider"

I think I solved the issue in my local, and I'm gonna do a Pull Request with my propossed solution.

#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
Custom ProvisiningExtensibilityHandler GetTokens method is invoked.

#### Observed Behavior
Custom ProvisiningExtensibilityHandler GetTokens method is NOT invoked. If you set a breakpoint to that method, you'll see is not invoked never. Seems is because some code in the ExtensibilityManager is expecting an object with the old interface "IProvisioningExtensibilityProvider".

#### Steps to Reproduce
_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

#### Submission Guidelines
_Delete this section after reading_
- All suggestions or bugs are welcome, please let us know what's on your mind.
- If you are reporting any issues around PnP Core Component, please reproduce the issue with latest release.
- If you are reporting issue around PnP Provisioning Engine, please share the xml template, if possible.
- If you are reporting an issue around any of the samples, please ensure that you have clear reference on the sample and possibly code file, which should be fixed.
- If you have a general question, please use the [PnP Yammer Group](http://aka.ms/OfficeDevPnPYammer).
- Remember to include sufficient details and context.
- If you have multiple suggestions or bugs please submit them in seperate bugs so we can track resolution.

Thanks for your contribution! Sharing is caring.

**Comment by PaoloPia** [comment]
Hi Luis,
Thanks for your contribution. The proposed solutions looks good and I will merge it.
