### ISSUE TITLE
Provisioning Engine - Sequence

### ISSUE THREAD

**Issue by TVDKoni** [OfficeDev/PnP-Sites-Core#700]
[ X] Office 365 / SharePoint Online
Tried to import a template containing a seuence
` 
<pnp:Sequence ID="SEQUENCE" SequenceType="Synchronous">
	  <pnp:SiteCollection Language="1033" PrimarySiteCollectionAdmin="admin" TimeZone="4" Title="Flexdesk Projects" Url="https://{parameter:O365TenantName}.sharepoint.com/sites/FlexdeskP" MembersCanShare="true"> 
		<pnp:Templates>
		  <pnp:ProvisioningTemplateReference ID="TEMPLATE15" />
		</pnp:Templates>
	  </pnp:SiteCollection>
	  <pnp:Site Language="1033" TimeZone="4" Title="{resource:SiteTitle16}" Url="O365" QuickLaunchEnabled="true"> 
		<pnp:Templates>
		  <pnp:ProvisioningTemplateReference ID="TEMPLATE16" />
		</pnp:Templates>
	  </pnp:Site>
  </pnp:Sequence>
`

No error message may also nothing created. Is the sequence node not yet supported?

**Comment by PaoloPia** [comment]
Hi,
Unfortunately, as you argued, the sequence node is not yet supported.

**Comment by oozoo-solutions** [comment]
Is there any plans to implement any of this at all?
I noticed that the sequence XML isn't even parsed into the ProvisioningTemplate model. I can't even implement any bits I want without making the changes to Core to parse this out of the template
