### ISSUE TITLE
Web Titles are left blank after upgrading to latest 201608

### ISSUE THREAD

**Issue by casvaniersel** [OfficeDev/PnP-Sites-Core#704]
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[x] Bug
[ ] Enhancement

#### Environment
[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[x] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 
Farm runs on 15.0.4805.1000 ​-> March 2016 CU

#### Expected or Desired Behavior
Subsites (webs) are created using the Provisioning Engine with a given Title (in code), after applying the Provisioning Template the Title remains intact. 

#### Observed Behavior
When Web.CreateWeb() is called the title argument is passed in correct. After the Web is created our Provisioning Template is applied with these WebSettings. After the process is completed, the Title of the new Web is emptied. 

`<pnp:WebSettings NoCrawl="false" WelcomePage="Paginas/Start.aspx" SiteLogo="{sitecollection}/_catalogs/masterpage/Images/logo.png" AlternateCSS="{sitecollection}/_catalogs/masterpage/css/branding.min.css" />`

#### Steps to Reproduce
1. Create a new Web with these settings based on Core 1606.3 (June)
2. Web is created with Title intact
3. Create another Web with these settings based on Core 1608 (August)
4. Web is created with Title emptied

#### Suggestions
- Maybe the Title attribute is forced even though it's optional in Latest PnP release? 
- I've tried to upgrade the provisioning template to latest version 2016-05 but this has no effect on the Web Title

**Comment by jansenbe** [comment]
Hi Cas,

In previous releases the title was never set and in the August 2016 release we adjusted that. I've updated that code to only set the title when the engine gets a non-null and non-blank value. Thanks for reporting this. You can use the dev branch code if you immediately need to the fix or alternatively wait until the first week of September for a new release.

**Comment by casvaniersel** [comment]
Hey Bert,

Thanks for the quick fix!
