### ISSUE TITLE
Keep the existing site title when deploying a site based on a PnP Provisioning template without a <pnp:WebSettings.title attribute

### ISSUE THREAD

**Issue by haroldvandekamp** [OfficeDev/PnP-Sites-Core#737]
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[X] SharePoint 2016
[X] SharePoint 2013

#### Expected or Desired Behavior
After setting the <pnp:WebSettings> without the Title attribute, we would expect that the existing site title stays the same.

#### Observed Behavior
After setting the <pnp:WebSettings> without the Title attribute, the site title disappears. The title attribute is optional, but it looks like it is not ignored when it's not provided. 

Found different behaviour regarding the Site Title in the August 2016 OfficeDev PnP release compared to previous releases. Both targetting the targeting the 2015/12 ProvisioningSchema. In the past the existing site title didn't changed, now it changes to an empty title. 

I've worked around this by specifying the <pnp:WebSettings.Title> attribute, but that is not working on the long run. We want to make sure that an existing site with a title keeps it's title when a provisioning template doesn't have a title provided.

See also this image for more detail
![image](https://cloud.githubusercontent.com/assets/11357196/18318556/65f39afa-7522-11e6-9acb-83ff6f78bdd2.png)

#### Steps to Reproduce
Deploy a provisioning template with a pnp:WebSettings element without providing the title attribute:

`<pnp:WebSettings RequestAccessEmail="sharepoint@company.com" NoCrawl="false" WelcomePage="SitePages/Introductiepagina.aspx" SiteLogo="{site}/SiteAssets/Logo.png" AlternateCSS="{site}/SiteAssets/Rootsite.css" MasterPageUrl="{masterpagecatalog}/seattle.master" CustomMasterPageUrl="{masterpagecatalog}/seattle.master" />`

instead of
`<pnp:WebSettings RequestAccessEmail="sharepoint@company.com" NoCrawl="false" WelcomePage="SitePages/Introductiepagina.aspx" SiteLogo="{site}/SiteAssets/Logo.png" AlternateCSS="{site}/SiteAssets/Rootsite.css" MasterPageUrl="{masterpagecatalog}/seattle.master" CustomMasterPageUrl="{masterpagecatalog}/seattle.master" Title="My Site Title" />`

**Comment by erwinvanhunen** [comment]
Thank you for reporting this. We already fixed this in the dev branch and will be released after Friday's master merge. I will close this issue.
