### ISSUE TITLE
Site title is blanked when the websettings element is used

### ISSUE THREAD

**Issue by paulbuzzby** [OfficeDev/PnP-Sites-Core#739]
#### Which PnP repository to report the issue?

- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

*You can delete this section after you have confirmed target repository for your submission.*

#### Category
[X ] Bug
[ ] Enhancement

#### Environment
[ X] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
If the title attribute is omitted then the title should remain

#### Observed Behavior
When using the websettings element in a PnP template the site title gets set to blank

#### Steps to Reproduce
Use the websettings element to update something against a site, do not include or use the Title attribute. Observe that the site title is set to blank

Seems that this latest release has a lot of issues as this is the second issue i have had with this releases.

**Comment by erwinvanhunen** [comment]
Hi Paul,

Thank you for reporting this issue.

We fixed this issue earlier, and it will be available in the upcoming release of the cmdlets and core library after tomorrow's master merge.
