### ISSUE TITLE
How to add a list item in office dev pnp?

### ISSUE THREAD

**Issue by khha** [OfficeDev/PnP-Sites-Core#818]
I did use pnp-Powershell alot. It is there possible to create a new list item by this command "Add-SPOListItem". But now I would like to use the c# CSOM pnp. Is it there also possible to create a new list item?

**Comment by erwinvanhunen** [comment]
We do not have similar functionality in PnP, as it's available by default in CSOM:

```csharp
var list = clientContext.Web.GetListByTitle("YourList");
var item = list.AddItem();
item["Title"] = "Your new title";
item.Update();
clientContext.ExecuteQuery();
```

I will close this issue.
