### ISSUE TITLE
Get-SPOProvisioningTemplate : Cannot find stub for type with id "{1554af8c-7213-418c-a4a8-b06e7603c68a}". 

### ISSUE THREAD

**Issue by yvonne70** [OfficeDev/PnP-Sites-Core#824]
Hi,

I am trying to export a site template using your Provisioning model:

using this Powershell:
import-module C:\TEMP\SharePointPnPPowerShell2013\Modules\SharePointPnPPowerShell2013
#### Region : Variables that can be changed ####
$SiteUrl = "https://mirai-dev:100/sites/UAT/"
#### End region ####

Connect-SPOnline -Url $SiteUrl 

cls

Get-SPOProvisioningTemplate -ExcludeHandlers AuditSettings -Out C:\DEV\SuntoryDEV2.xml

However I get the error below:

Get-SPOProvisioningTemplate : Cannot find stub for type with id "{1554af8c-7213-418c-a4a8-b06e7603c68a}". The specified server may not support APIs used in 
this operation.

**Comment by yvonne70** [comment]
Turned on logging and now get this
Cannot bind parameter 'Schema'. Cannot convert value "AuditSettings" to type 
"OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLPnPSchemaVersion". Error: "Unable to match the identifier name AuditSettings to 
a valid enumerator name.  Specify one of the following enumerator names and try again: LATEST, V201503, V201505, V201508, V201512"
At C:\Users\E-HARYX001\Desktop\ExportSiteTempate.ps1:22 char:46
+ Get-SPOProvisioningTemplate -Handlers Fields AuditSettings -Out C:\DEV\SuntoryDE ...

**Comment by VesaJuvonen** [comment]
This means that you are most likely running older version of SharePoint 2013, than 2015 April CU, which is the baseline for the PnP engine. This means that you should double check the exact version what you are using in your SharePoint side, but exception indicates clearly that you don't have AuditSettings CSOM support in your server side environment.

**Comment by yvonne70** [comment]
Yes I have checked my SharePoint version and I am on service pack 2 from a few years ago, so I will install patches/upgrades. So thanks for the pointer.

**Comment by VesaJuvonen** [comment]
Closing this for now, if issue persists after upgrade, let's reopen the issue.
