### ISSUE TITLE
Custom Action 

### ISSUE THREAD

**Issue by suz7777** [OfficeDev/PnP-Sites-Core#826]
#### Which PnP repository to report the issue?
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell
#### Category
[x ] Bug
[ ] Enhancement

#### Environment
[x ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[ ] SharePoint 2013

#### Expected or Desired Behavior
In the NEW Modern Site Settings on a traditional sharepoint site...
This works when applying a custom action to the gear: (i removed leading carrot (<) and/or slash)
"          pnp:CustomAction Name="{fb19a277-e1b5-4b32-9820-084278ddad00}" Description="3M Site Request page" Group="SiteActions" Location="Microsoft.SharePoint.StandardMenu" Title="Create Sub site" Sequence="101" Rights="" Url="https://skydrive3m.sharepoint.com/sites/3MAdm/RAS/Lists/DWP%20SiteRequest/NewForm.aspx" RegistrationType="None">
            pnp:CommandUIExtension />
          pnp:CustomAction>
this does not work - but does work in a classic site look:
pnp:CustomAction Name="{559b16ea-0a4e-44f2-879d-358a5c385e39}" Group="SiteActions" Location="Microsoft.SharePoint.StandardMenu" Title="DWP Page Creation" Sequence="100" Rights="" Url="javascript:dwpPageCreation.init();" RegistrationType="None">
pnp:CommandUIExtension />
pnp:CustomAction>
"
#### Observed Behavior
both above custom actions work in the classic site look and feel - but the second does not work in the modern look.  we find that anytime we put javascript in the custom action it does not appear in the gear.

#### Steps to Reproduce
Create a PNP script with custom action and use the following
      if ($applyCustomAction) {
		write-host "custom action template - $caXml" 
		if ($clearCustomActions) {
			Get-SPOCustomAction
			Get-SPOCustomAction | foreach { Remove-SPOCustomAction $_.id }
		}
		Apply-SPOProvisioningTemplate -Path $caXml
		Apply-SPOProvisioningTemplate -Path $caXml2
		write-host "Successfully applied custom action template - $caXml and $caXml2 " BLUE
	}

**Comment by erwinvanhunen** [comment]
Thank you for reporting this. We are aware of the issue, it's unfortunately the modern sites that cause this, or rather, does not support this. It's not as such an issue with the engine itself. We are currently working on updated guidance and are working on changes in the provision engine to detect a modern site. If provisioning to a modern site we will have to limit the functionality of the engine to a subset of the features.

**Comment by suz7777** [comment]
are you aware of any other limitations with the modern sites and provisioning? is there an FAQ we can review?

**Comment by VesaJuvonen** [comment]
There's two things in this discussion. A Modern site and then modern UX with libraries, lists and site contents. Modern experiences on the classic site on lists/libraries do not support any level of JavaScript injection. There's work being done in the engineering around this, but we do not have exact timelines, which we can share. Following is a great blog post around these limitations from dev.office.com/blogs - https://dev.office.com/blogs/update-on-modern-document-libraries-and-extensiblity. 

Modern site is however something that's still officially in the queue to be released. That will have similar limitations with first released version, until similar scenarios as with JS embedding can be achieved using SharePoint Framework (railed experiences). Modern sites have also NoScript setting enabled by default, without possibility to disable that, so following limitations are then valid - https://support.office.com/en-us/article/Turn-scripting-capabilities-on-or-off-1f2c515f-5d7e-448a-9fd7-835da935584f. 

Like we mentioned publicly also in Ignite, modern sites will land soon for first release tenants. It's also important to notice that classic site with modern libraries/lists is completely different thing than fully native modern sites. When modern sites are enabled, we are absolutely looking for community input around the released capabilities.

From PnP side, we will release more details when the modern sites move to First Release. We can't unfortunately share any non-public information at this point.

**Comment by erwinvanhunen** [comment]
This issue was moved to OfficeDev/PnP-PowerShell#531
