### ISSUE TITLE
Calculated Columns do not extract properly

### ISSUE THREAD

**Issue by suz7777** [OfficeDev/PnP-Sites-Core#828]
#### Which PnP repository to report the issue?
- PnP PowerShell - https://github.com/OfficeDev/PnP-PowerShell

*You can delete this section after you have confirmed target repository for your submission.*

#### Category
[ x] Bug
[ ] Enhancement

#### Environment
[ x] Office 365 / SharePoint Online

If SharePoint on-premises, what's exact CU version: 

#### Expected or Desired Behavior
Calculated Columns with Publishing Start/End date to not extract properly / do not provision 

#### Observed Behavior
export behavior - the calculated column extracts as follows:
        <Field Type="Calculated" DisplayName="Review Date" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="1033" ResultType="DateTime" ReadOnly="TRUE" Group="DWPCorp Site Columns" ID="{30e2d19b-52b4-4d17-bc2c-9cff1aa8fa2c}" SourceID="{49b1ff83-fcbf-447d-97e9-0d3e6f3a9a03}" StaticName="DWPCorpReviewDate" Name="DWPCorpReviewDate" Required="FALSE">
          <Formula>=DATE(YEAR([{fieldtitle:[{fieldtitle:[{fieldtitle:PublishingStartDate}]}]}])+1,MONTH([{fieldtitle:[{fieldtitle:[{fieldtitle:PublishingStartDate}]}]}])+6,DAY([{fieldtitle:[{fieldtitle:[{fieldtitle:PublishingStartDate}]}]}]))</Formula>
        </Field>

it should extract like:
        <Field Type="Calculated" DisplayName="__Review Date" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="1033" ResultType="DateTime" Group="00-DWPCorp Site Columns" ID="{79b235a7-4397-4e3e-a0e0-19548ddf3110}" SourceID="{7eb3055d-b79b-47f0-9b50-7b00acc559a7}" StaticName="DWP_ReviewDate" Name="DWP_ReviewDate" Required="FALSE" AllowDeletion="TRUE" ReadOnly="TRUE">
          <Formula>=DATE(YEAR([Scheduling Start Date])+1,MONTH([Scheduling Start Date])+6,DAY([Scheduling Start Date]))</Formula>
        </Field>

if i extract/add w/o manually fixing the XML, the field is corrupted.

#### Steps to Reproduce
Create a field with a calculated column
Get-SPOProvisioningTemplate -out $tpFields -Handlers Fields -Force
Apply-SPOProvisioningTemplate -out $tpFields -Handlers Fields -Force

**Comment by erwinvanhunen** [comment]
Hi! Thank you for reporting this. Very good catch. I just merged a fix to this in the dev branch and I will close this issue.

**Comment by suz7777** [comment]
i have downloaded the latest code - this is the information i see when exporting a Field.

=DATE(YEAR([{fieldtitle:[{fieldtitle:[{fieldtitle:PublishingStartDate}]}]}])+1,MONTH([{fieldtitle:[{fieldtitle:[{fieldtitle:PublishingStartDate}]}]}])+6,DAY([{fieldtitle:[{fieldtitle:[{fieldtitle:PublishingStartDate}]}]}]))

**Comment by suz7777** [comment]
Thanks ! i just tested this and it appears it works correctly for SiteCollection Columns
        <Field Type="Calculated" DisplayName="__Review Date" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="1033" ResultType="DateTime" Group="00-DWPCorp Site Columns" ID="{79b235a7-4397-4e3e-a0e0-19548ddf3110}" SourceID="{7eb3055d-b79b-47f0-9b50-7b00acc559a7}" StaticName="DWP_ReviewDate" Name="DWP_ReviewDate" Required="FALSE" AllowDeletion="TRUE" ReadOnly="TRUE">
          <Formula>=DATE(YEAR([Scheduling Start Date])+1,MONTH([Scheduling Start Date])+6,DAY([Scheduling Start Date]))</Formula>
        </Field>

but... for content type hub columns, it appears to have the old formula
<Field Type="Calculated" DisplayName="Review Date" EnforceUniqueValues="FALSE" Indexed="FALSE" Format="DateOnly" LCID="1033" ResultType="DateTime" ReadOnly="TRUE" Group="DWPCorp Site Columns" ID="{30e2d19b-52b4-4d17-bc2c-9cff1aa8fa2c}" SourceID="{49b1ff83-fcbf-447d-97e9-0d3e6f3a9a03}" StaticName="DWPCorpReviewDate" Name="DWPCorpReviewDate" Required="FALSE">
          <Formula>=DATE(YEAR([{fieldtitle:[{fieldtitle:[{fieldtitle:PublishingStartDate}]}]}])+1,MONTH([{fieldtitle:[{fieldtitle:[{fieldtitle:PublishingStartDate}]}]}])+6,DAY([{fieldtitle:[{fieldtitle:[{fieldtitle:PublishingStartDate}]}]}]))</Formula>
        </Field>
