### ISSUE TITLE
Missing parameters on 

### ISSUE THREAD

**Issue by khha** [OfficeDev/PnP-Sites-Core#831]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. If you have a actual question, we would ask you to use PnP Yammer group at http://aka.ms/OfficeDevPnPYammer. Thanks!
#### Which PnP repository to report the issue?
- PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core

_You can delete this section after you have confirmed target repository for your submission._
#### Category

[ ] Bug
[ ] Enhancement
#### Environment

[ ] Office 365 / SharePoint Online
[ ] SharePoint 2016
[V ] SharePoint 2013

In pnp-PowerShell it is possible to add parameters to the function ApplyProvisioningTemplate. Is this also possible with pnp core csom?

Here is an example of the pnp-Powershell function: 

`Apply-SPOProvisioningTemplate -Path "Template.xml" -Parameters @{"SiteOwnerMail"="someone@example.com"}`

Here is an example of my pnp core csom:

```
XMLTemplateProvider provider = new XMLFileSystemTemplateProvider(String.Format(@"{0}\Templates\", AppDomain.CurrentDomain.BaseDirectory), "");

            if (provider != null)
            {
                var template = provider.GetTemplate("PeriodeTemplate.xml");

                if (template != null)
                {
                    newWeb.ApplyProvisioningTemplate(template);

                    return true;
                }
            }
```

**Comment by erwinvanhunen** [comment]
Yes, that's very possible:

```csharp
var template = provider.GetTemplate("PeriodeTemplate.xml");
template.Parameters.Add("SiteOwnerEmail","someone@example.com");
```

**Comment by khha** [comment]
Thanks it works!
