### ISSUE TITLE
Provisioning Engine: Referencing a Field in a Content Type results in an error

### ISSUE THREAD

**Issue by olemp** [OfficeDev/PnP-Sites-Core#91]
Similiar issue to https://github.com/OfficeDev/PnP-Sites-Core/issues/72

The error has occured with Taxonomy Fields, Choice Fields and Calculated Fields, so I think it's a general issue for all FieldRefs in Content Types.

Yammer thread: https://www.yammer.com/itpronetwork/#/Threads/show?threadId=594295724

I'm getting the following error:
Apply-SPOProvisioningTemplate : The property or field 'Id' has not been initialized. It has not been requested or the request has
not been executed. It may need to be explicitly requested.
At line:1 char:1
+ Apply-SPOProvisioningTemplate .\template.xml -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-SPOProvisioningTemplate], PropertyOrFieldNotInitializedException
    + FullyQualifiedErrorId : EXCEPTION,OfficeDevPnP.PowerShell.Commands.Branding.ApplyProvisioningTemplate

**Comment by olemp** [comment]
I've created a pull request for a proposed solution https://github.com/OfficeDev/PnP-Sites-Core/pull/93

**Comment by PaoloPia** [comment]
Thanks, we're following up with the PR#93 and subsequent PRs.
