### ISSUE TITLE
How to change deployment location of files(css, images, etc.)

### ISSUE THREAD

**Issue by petertoman80** [OfficeDev/PnP-Sites-Core#96]
Hi,
I didn't find a solution how deploy files other than to copy them first to /bin folder and then remote provisioning engine just pick them up from there.
Is there any way how to tell the provisioning engine to look the files elsewhere, for example directly from where they are stored in Visual Studio solution?

Thanks

**Comment by PaoloPia** [comment]
Hi, while applying the template you can use the Connector property of that template to load files. While extracting the template, you can use the FileConnector property of the ProvisioningTemplateCreationInformation that you can pass to the GetProvisioningTemplate method.

**Comment by VesaJuvonen** [comment]
Will close up the issue now. Would also suggest to use the Yammer group for usage questions, since we have more activities at that side with more than 3500 other active members. You can find PnP Yammer group from http://aka.ms/OfficeDevPnPYammer.
