### ISSUE TITLE
Managed Metadata fields are not exported properly

### ISSUE THREAD

**Issue by PieterVeenstra** [OfficeDev/PnP-Sites-Core#98]
As I had some issues importing my templates with Taxonomy fields I ran the following test. 
I've created two site collections (both publishing portals)

/sites/source
/sites/target

Then I ran the following PowerShell:

Connect-SPOnline -Url https://pieterveenstratest.sharepoint.com/sites/source -Credentials $credentials
 
 $web = Get-SPOWeb
 Get-SPOProvisioningTemplate -Out C:\Template.xml -Schema V201505 -Web $web

 Connect-SPOnline -Url https://pieterveenstratest.sharepoint.com/sites/target  -Credentials $credentials
 
 $targetweb = Get-SPOWeb

 Apply-SPOProvisioningTemplate -Path  C:\Template.xml -Web $targetweb  

This is all working fine.

Then I added a Managed Metadata field to my source site and reran the above PowerShell. My template.xml contains the following section:

**< Field Type="TaxonomyFieldType" DisplayName="testMM" List="Lists/TaxonomyHiddenList" WebId="fbb2a609-6c5b-4306-994d-cf6818118687" ShowField="Term1033" Required="FALSE" EnforceUniqueValues="FALSE" Group="Custom Columns" ID="{f4a950ec-87d1-4d00-9243-a59ad779c943}" SourceID="{fbb2a609-6c5b-4306-994d-cf6818118687}" StaticName="testMM" Name="testMM">
          < Default>
          < /Default>
          < Customization>
            < ArrayOfProperty>
              < Property>
                < Name>SspId< /Name>
                < Value xmlns:q1="http://www.w3.org/2001/XMLSchema" p4:type="q1:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">6ec0c05d-3e14-4cf1-b1f5-317f9653c8c2< /Value>
              < /Property>
              < Property>
                < Name>GroupId< /Name>
              < /Property>
              < Property>
                < Name>TermSetId< /Name>
                < Value xmlns:q2="http://www.w3.org/2001/XMLSchema" p4:type="q2:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">766f7f55-9e17-4c7b-851a-2641685c57ec< /Value>
              < /Property>
              < Property>
                < Name>AnchorId< /Name>
                < Value xmlns:q3="http://www.w3.org/2001/XMLSchema" p4:type="q3:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">b1345b59-65ed-499b-b1cb-b9571f8bfcfd< /Value>
              < /Property>
              < Property>
                < Name>UserCreated< /Name>
                < Value xmlns:q4="http://www.w3.org/2001/XMLSchema" p4:type="q4:boolean" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">false< /Value>
              <  /Property>
              < Property>
                < Name>Open< /Name>
                < Value xmlns:q5="http://www.w3.org/2001/XMLSchema" p4:type="q5:boolean" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">false< /Value>
              < /Property>
              <  Property>
                < Name>TextField< /Name>
                < Value xmlns:q6="http://www.w3.org/2001/XMLSchema" p4:type="q6:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">{3cc476ca-817b-45a3-82b7-1117226ea6af}< /Value>
              <  /Property>
              < Property>
                < Name>IsPathRendered< /Name>
                < Value xmlns:q7="http://www.w3.org/2001/XMLSchema" p4:type="q7:boolean" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">false</Value>
              < /Property>
              < Property>
                < Name>IsKeyword< /Name>
                < Value xmlns:q8="http://www.w3.org/2001/XMLSchema" p4:type="q8:boolean" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">false</Value>
              < /Property>
              < Property>
                < Name>TargetTemplate< /Name>
              < /Property>
              < Property>
                < Name>CreateValuesInEditForm< /Name>
                < Value xmlns:q9="http://www.w3.org/2001/XMLSchema" p4:type="q9:boolean" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">false< /Value>
              < /Property>
              <  Property>
                < Name>FilterAssemblyStrongName< /Name>
                < Value xmlns:q10="http://www.w3.org/2001/XMLSchema" p4:type="q10:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">Microsoft.SharePoint.Taxonomy, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c</Value>
              < /Property>
              < Property>
                < Name>FilterClassName< /Name>
                < Value xmlns:q11="http://www.w3.org/2001/XMLSchema" p4:type="q11:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">Microsoft.SharePoint.Taxonomy.TaxonomyField< /Value>
              < /Property>
              <  Property>
                < Name>FilterMethodName</Name>
                < Value xmlns:q12="http://www.w3.org/2001/XMLSchema" p4:type="q12:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">GetFilteringHtml</Value>
              < /Property>
              < Property>
                < Name>FilterJavascriptProperty</Name>
                < Value xmlns:q13="http://www.w3.org/2001/XMLSchema" p4:type="q13:string" xmlns:p4="http://www.w3.org/2001/XMLSchema-instance">FilteringJavascript< /Value>
              < /Property>
            < /ArrayOfProperty>
          <  /Customization>
        < /Field>**

The hidden text field with guid 3cc476ca-817b-45a3-82b7-1117226ea6af however is not included in my template.xml.

Within the ObjectField.cs I found code removing the hidden Taxonomy fields.  (line 210). Why are these hidden fields removed? Are these not required as part of the import?

**Comment by VesaJuvonen** [comment]
This should be now fixed with the updated Oct release. If that's not the case, please re-open the issue. Thx for reporting the issue.
